/**
 * The per-diagram layout worklist.
 *
 * Paul, 2026-09-04: "we need a list of specific issues for each diagram so we
 * know what has to be fixed to take a diagram off the list (hopefully not adding
 * any in the process!!)".
 *
 * The corpus check (tests/bpmn/layout-corpus.test.ts) knows the COUNT per
 * diagram, which is enough to stop a regression but not enough to act on. This
 * writes what each of those defects actually IS, so a diagram can be picked up
 * and finished. Deterministic and free — it replays stored AI plans, no AI call.
 *
 *   npx tsx scripts/layout-worklist.ts            # rewrite the worklist
 *   npx tsx scripts/layout-worklist.ts --check    # fail if it is out of date
 */
import * as fs from "fs";
import * as path from "path";
import { layoutBpmnDiagram } from "@/app/lib/diagram/bpmnLayout";
import { findLayoutViolations, findReadabilityViolations } from "@/app/lib/diagram/checks/layoutViolations";
import type { DiagramData } from "@/app/lib/diagram/types";

const DIR = path.join(process.cwd(), "tests", "fixtures", "layout-corpus");
const OUT = path.join(process.cwd(), "tests", "fixtures", "layout-corpus", "WORKLIST.md");

const files = fs.readdirSync(DIR).filter((f) => f.endsWith(".plan.json")).sort();
const byDiagram: { file: string; name: string; issues: string[] }[] = [];

for (const f of files) {
  const j = JSON.parse(fs.readFileSync(path.join(DIR, f), "utf8"));
  const plan = j.diagrams?.[0]?.data?.aiGeneration?.plan ?? j.plan;
  const r = layoutBpmnDiagram(plan.elements, plan.connections);
  const data = { elements: r.elements, connectors: r.connectors } as DiagramData;
  const vs = [...findLayoutViolations(data), ...findReadabilityViolations(data)];
  if (!vs.length) continue;
  byDiagram.push({
    file: f,
    name: j.diagrams?.[0]?.name ?? f.replace(".plan.json", ""),
    issues: vs.map((v) => (typeof v === "string" ? v : (v as { detail?: string; message?: string }).detail
      ?? (v as { message?: string }).message ?? JSON.stringify(v))),
  });
}

const total = byDiagram.reduce((n, d) => n + d.issues.length, 0);
const lines: string[] = [
  "# Layout worklist — what is left to fix",
  "",
  "Generated by `npx tsx scripts/layout-worklist.ts`. Do not hand-edit.",
  "",
  "Each entry is a diagram in the layout corpus that still lays out with a",
  "readability defect. The corpus test pins the COUNT per diagram so none can get",
  "worse; this says what the defects ARE so one can be picked up and finished.",
  "",
  "A diagram leaves this list when its count reaches zero — at which point its",
  "entry in `KNOWN` (tests/bpmn/layout-corpus.test.ts) is deleted.",
  "",
  `**${byDiagram.length} diagram(s) with ${total} defect(s)**, out of ${files.length} in the corpus.`,
  "",
];
for (const d of byDiagram) {
  lines.push(`## ${d.name}  \`${d.file}\` — ${d.issues.length}`, "");
  for (const i of d.issues) lines.push(`- ${i}`);
  lines.push("");
}

const body = lines.join("\n");
if (process.argv.includes("--check")) {
  const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, "utf8") : "";
  if (current.trim() !== body.trim()) {
    console.error("WORKLIST.md is out of date — run: npx tsx scripts/layout-worklist.ts");
    process.exit(1);
  }
  console.log("WORKLIST.md is current");
} else {
  fs.writeFileSync(OUT, body);
  console.log(`wrote ${OUT} — ${byDiagram.length} diagram(s), ${total} defect(s)`);
}
