"use client";

/**
 * The Voice Assist session — moved UNEDITED out of DiagramEditor.tsx (Stage 4
 * of mobile voice, 2026-09-29) so the desktop editor and the phone can share it.
 * Generated by tests/voice-session/voiceSessionFrame.mjs (buildHookSource) from
 * the editor's block; the behaviour tests in tests/voice-session/ ran this text.
 *
 * RULES (the reasons many earlier bugs were fixed):
 *   • Call it exactly where the block was — after the editor's own hooks that
 *     it reads, before those that read it: its 11 effects keep their order
 *     among the editor's (gold flash → touched → settle → drain …).
 *   • One apply → exactly one log line, in the same tick (appliedOpsRef).
 *   • Refs re-assigned during render (runAbraCommandRef …) are how the mic's
 *     callbacks, made once per toggle, reach the latest code.
 *   • Mixed freshness is deliberate: the router reads the render's `data`,
 *     the flows read elementsRef.
 */
import type { CommandLogEntry } from "@/app/components/canvas/VoiceAssistBar";
import { nanoid } from "@/app/hooks/useDiagram";
import type { TemplateFlow, TemplateReport } from "@/app/hooks/voiceTemplateTypes";
import { aiInventedRename, INVENTED_RENAME_REFUSAL } from "@/app/lib/assist/aiGuards";
import { applyAssistOps as applyAssistOpsTo, type AssistApplyContext, type AssistDiagramActions, assistSettingsOf, type RenameFlow } from "@/app/lib/assist/applyAssistOps";
import { type BoundaryMemory, readBoundaryFollowUp } from "@/app/lib/assist/boundaryFollowUp";
import { parseCommand } from "@/app/lib/assist/commandGrammar";
import { type CommandVerdict, type TouchBox, touchedFor } from "@/app/lib/assist/commandLog";
import { needsConfirmation, parseConfirmation } from "@/app/lib/assist/confirm";
import { type ArmedCapture, badgesOnScreen, type CaptureLedger, captureState, captureStoppedSummary, newCaptureLedger, projectFlow, settleArm } from "@/app/lib/assist/debugCapture";
import { buildDebugSessionFile, debugSessionFilename, type DebugSnapshot, serialiseDebugSession, type SnapshotRole } from "@/app/lib/assist/debugSessionFile";
import { parsePickAnswer, type PickFlow, substituteRef } from "@/app/lib/assist/disambiguate";
import { parseNumberList } from "@/app/lib/assist/numberList";
import { adjustOp, collectDividers, type DividerFlow, type DividerMemory, dividerOp, dividerReply, dividerRulers, explainDividerMiss, movedPx, readDividerUtterance } from "@/app/lib/assist/dividerFlow";
import { FRAGMENT_CONTINUE_MS, FRAGMENT_MAX_WAITS, FRAGMENT_SILENCE_MS } from "@/app/lib/assist/fragmentBuffer";
import { batchFlashes, type FlashBox, flashTargets, isGoldFlashOn, setGoldFlash } from "@/app/lib/assist/goldFlash";
import { isIncompleteCommand } from "@/app/lib/assist/incompleteCommand";
import { type MessagePick, parseMessageAnswer, resolveMessageAnswer } from "@/app/lib/assist/messageTargets";
import { type AssistOp, validateOps } from "@/app/lib/assist/ops";
import { interruptsPick } from "@/app/lib/assist/pickInterrupt";
import { humaniseIds, notUnderstoodMessage } from "@/app/lib/assist/refMentions";
import { collectRenameTargets, isClearLabelWord, type RenameType } from "@/app/lib/assist/renameTargets";
import { ID_REF_PREFIX } from "@/app/lib/assist/resolveRef";
import { joinSpelledLetters } from "@/app/lib/assist/spelledWord";
import { leadingSpokenNumber, restoreLostOneNumber } from "@/app/lib/assist/spokenNumber";
import { isFlowEndWord, isMicStopWord } from "@/app/lib/assist/stopWords";
import { TEMPLATE_BEFORE_REFUSAL } from "@/app/lib/assist/templatePhrase";
import { parseTemplateAnswer, type TemplateCard, templateScrollReply, templateScrollTarget } from "@/app/lib/assist/templatePick";
import { isVoiceDebugOn } from "@/app/lib/assist/voiceDebug";
import type { SymbolColorConfig } from "@/app/lib/diagram/colors";
import type { DisplayMode } from "@/app/lib/diagram/displayMode";
import { subtypeFingerprint } from "@/app/lib/diagram/elementSubtypes";
import { capitaliseFirstWord, isFullyCapitalised, titleCaseName } from "@/app/lib/diagram/nameCase";
import { type Connector, type DiagramData, type DiagramElement, type DiagramType, PRODUCT_VERSION } from "@/app/lib/diagram/types";
import { type DictationHandle, startDictation } from "@/app/lib/dictation";
import { diagramKeyterms } from "@/app/lib/dictation/diagramKeyterms";
import { type Dispatch, type MutableRefObject, type SetStateAction, useCallback, useEffect, useMemo, useRef, useState } from "react";



/** What the host screen supplies: its useDiagram edit actions and its editor values. */
export interface VoiceSessionHost extends Pick<AssistDiagramActions, "addConnector" | "addElementGated" | "addLaneAt" | "addPool" | "alignElements" | "clearDiagram" | "compressLane" | "compressPool" | "convertTaskSubprocess" | "deleteConnector" | "reverseConnector" | "deleteElement" | "elementsMoveEnd" | "expandLane" | "extendPools" | "insertSpace" | "laneBoundaryMoveEnd" | "moveElements" | "moveLane" | "moveLaneBoundary" | "movePoolTo" | "removeSpace" | "resizeElement" | "resizeElementEnd" | "setEventBoundary" | "splitLaneEven" | "splitPoolEven" | "swapLane" | "swapPools" | "undo" | "unwrapSubprocess" | "updateConnectorEndpoint" | "updateConnectorLabel" | "updateLabel" | "updateProperties" | "wrapInContainer" | "wrapInPool" | "wrapInSubprocess"> {
  beginHistoryGroup: () => void;
  beginLabelEdit: (id: string) => void;
  cancelLabelEdit: () => void;
  connectorsRef: MutableRefObject<Connector[]>;
  data: DiagramData;
  diagramColorConfig: SymbolColorConfig;
  diagramId: string;
  diagramName: string;
  diagramType: DiagramType;
  displayMode: DisplayMode;
  elementsRef: MutableRefObject<DiagramElement[]>;
  endHistoryGroup: () => void;
  handleExportJson: () => void | Promise<void>;
  nextStepRef: AssistApplyContext["refs"]["nextStepRef"];
  openTemplateWindowRef: AssistApplyContext["refs"]["openTemplateWindowRef"];
  riskCatalog: AssistApplyContext["riskCatalog"];
  selectedConnectorIdRef: MutableRefObject<string | null>;
  selectedIdsRef: MutableRefObject<string[]>;
  setSelectedConnectorId: Dispatch<SetStateAction<string | null>>;
  setSelectedElementIds: Dispatch<SetStateAction<Set<string>>>;
  /** Auto-connect (the phone's toggle): an add with no "after X" joins the selection / last element. Off by default. */
  autoConnect?: boolean;
  /**
   * Position-aware repair of a heard command (Voice Assist Help slice 5). Set by the editor once the
   * SuperAdmin's setting is known; null/absent means no repair. It only ever turns a command the parser
   * does NOT understand into one it does, and the session never calls it while a guided flow or a question
   * is open — those answers go to the flow, not to the parser.
   */
  repairCommandRef?: MutableRefObject<((heard: string) => { text: string; note: string | null }) | null>;
  /** The phone: 16 kHz capture and an automatic reconnect when the connection drops (mobile voice stage 7). */
  phone?: boolean;
}

export function useVoiceSession(host: VoiceSessionHost) {
  const {
    addConnector, addElementGated, addLaneAt, addPool, alignElements, beginHistoryGroup, beginLabelEdit, cancelLabelEdit, clearDiagram, compressLane, compressPool, connectorsRef, convertTaskSubprocess, data, deleteConnector, reverseConnector, deleteElement, diagramColorConfig, diagramId, diagramName, diagramType, displayMode, elementsMoveEnd, elementsRef, endHistoryGroup, expandLane, extendPools, handleExportJson, insertSpace, laneBoundaryMoveEnd, moveElements, moveLane, moveLaneBoundary, movePoolTo, nextStepRef, openTemplateWindowRef, removeSpace, resizeElement, resizeElementEnd, riskCatalog, selectedConnectorIdRef, selectedIdsRef, setEventBoundary, setSelectedConnectorId, setSelectedElementIds, splitLaneEven, splitPoolEven, swapLane, swapPools, undo, unwrapSubprocess, updateConnectorEndpoint, updateConnectorLabel, updateLabel, updateProperties, wrapInContainer, wrapInPool, wrapInSubprocess,
  } = host;
  const autoConnect = host.autoConnect === true;
  const phone = host.phone === true;

  // ── Voice Assist: live voice/typed command editing ──
  const [voiceAssistOn, setVoiceAssistOn] = useState(false);
  const [voiceLog, setVoiceLog] = useState<CommandLogEntry[]>([]);
  // The ops the command just applied, waiting for its log line. Every apply is
  // followed by exactly one log line in the same tick (the rule the debug
  // diff's "touched" already relies on), so the line written next is the one
  // they belong to — and no caller has to remember to pass them.
  const appliedOpsRef = useRef<AssistOp[] | null>(null);
  /**
   * The ONE way a line reaches the command log. It stamps `at`, recording or
   * not — a session saved later cannot be read without it — and carries the
   * ops just applied (plan: "The editor's single log closure … gains at and
   * ops"). A dozen direct appends once skipped the time.
   */
  const appendLog = useCallback((entry: Omit<CommandLogEntry, "id" | "at">) => {
    const ops = appliedOpsRef.current;
    appliedOpsRef.current = null;
    setVoiceLog((prev) => [...prev, { id: nanoid(), at: Date.now(), ...entry, ...(ops ? { ops } : {}) }]);
  }, []);
  const [voiceListening, setVoiceListening] = useState(false);
  const [abraEngine, setAbraEngine] = useState<"deepgram" | "browser" | null>(null);
  // Mic pressed but the recogniser not yet live (token + permission + socket):
  // the bar says "connecting…" so nobody talks into the gap.
  const [abraConnecting, setAbraConnecting] = useState(false);
  const [voiceInterim, setVoiceInterim] = useState("");
  const [voiceBusy, setVoiceBusy] = useState(false);
  /**
   * B4. `voiceBusy` is React state, so it is not true until the next render —
   * far too late to stop the NEXT utterance, which arrives from the mic
   * whenever the speaker stops for breath. The ref flips synchronously, and
   * anything spoken while a call is in flight waits its turn in the queue
   * instead of racing it.
   *
   * Without this, two sentences spoken over one AI call both applied against
   * the state from BEFORE the call, and their log lines interleaved. The text
   * box has been gated since b00e3c7b; the voice path never was.
   */
  const voiceBusyRef = useRef(false);
  const voiceQueueRef = useRef<string[]>([]);
  // Moves on at every stop (and diagram switch). An AI call remembers it when
  // it starts; a reply that arrives after a stop is dropped, not applied
  // (Paul's ruling, 2026-09-29: "stop" means stop).
  const voiceStopSeq = useRef(0);
  // Moves on at every diagram switch: a reply for the old diagram is dropped
  // SILENTLY — nobody said stop, and the old diagram's log is gone.
  const voiceSwitchSeq = useRef(0);
  // Wakes the drain effect (after the command runner): the queue drains one
  // command per render, never inside the call that just finished.
  const [voiceDrainTick, setVoiceDrainTick] = useState(0);
  const voiceLastId = useRef<string | null>(null);
  // The last lane-boundary / pool-edge command, for its follow-up — "sixty
  // pixels", "up by 98" (boundaryFollowUp.ts). applyAssistOps writes it; any
  // other command clears it (applyGrouped).
  const boundaryLastRef = useRef<BoundaryMemory | null>(null);
  // M5 — where the mouse last was on the canvas, in world coordinates. A REF,
  // not state: it is written on every pointer move and must never cause a
  // render. Null until the pointer has been over the canvas at all, which is
  // what lets "put a task here" refuse with a reason rather than guess (0,0).
  const pointerWorld = useRef<{ x: number; y: number } | null>(null);
  // stopAbraListening is defined after the command runner (it needs the buffer
  // flush); the runner reaches it through this ref.
  const stopAbraListeningRef = useRef<() => void>(() => {});
  // Remembers the last real command so "again" can repeat it (e.g. nudge again).
  const lastAbraOpsRef = useRef<AssistOp[]>([]);
  // Gold flashing. `goldFlashBeforeRef` holds the pre-command snapshot while the
  // reducer and React catch up; the effect below turns it into a set of boxes to
  // outline once the new elements have actually rendered. `runId` is what the
  // overlay watches — a number, so an unrelated re-render cannot re-trigger it.
  const goldFlashBeforeRef = useRef<FlashBox[] | null>(null);
  const [goldFlash, setGoldFlashState] = useState<{ runId: number; targets: FlashBox[] }>({ runId: 0, targets: [] });
  // DEBUG RECORDING (Paul, 2026-09-24). A second before-snapshot, armed on every
  // command rather than only the ones that flash: the evidence wants to know
  // what a rename or a delete did just as much as what a move did. Costs one
  // boolean read when the toggle is off, the same discipline as gestureTrace.
  const [voiceDebugRecording, setVoiceDebugRecording] = useState(false);
  const debugBeforeRef = useRef<TouchBox[] | null>(null);
  const [debugSnapshots, setDebugSnapshots] = useState<DebugSnapshot[]>([]);
  useEffect(() => { setVoiceDebugRecording(isVoiceDebugOn()); }, []);
  // Saved states of the diagram, automatic while recording (debugCapture.ts,
  // Paul's Q1 answer 2026-09-26). The reducer's state is immutable, so these
  // hold REFERENCES — a state is turned into text only for the size total and
  // when the session is saved or downloaded.
  const debugDataRef = useRef(data);
  debugDataRef.current = data;
  const debugLedgerRef = useRef<CaptureLedger>(newCaptureLedger());
  // A command in flight (settleArm, debugCapture.ts). The effect after the
  // re-render saves the "after" and ties both states to its entry.
  const debugArmRef = useRef<ArmedCapture | null>(null);
  // A destructive command waiting for "yes" (confirm.ts): the ops, what they
  // would do in words, and whether the AI interpreted them (for the log badge).
  const pendingConfirmRef = useRef<{ ops: AssistOp[]; what: string; viaAi: boolean } | null>(null);
  // "Cost so far": the session starts when the bar opens; the microphone's open
  // stretch is added live because its usage row is only written when it stops.
  const voiceSessionStart = useRef<Date>(new Date());
  const voiceMicOpenedAt = useRef<number | null>(null);
  useEffect(() => { if (voiceAssistOn) voiceSessionStart.current = new Date(); }, [voiceAssistOn]);
  const fetchAbraCost = useCallback(async () => {
    const live = voiceListening && voiceMicOpenedAt.current ? Math.round((Date.now() - voiceMicOpenedAt.current) / 1000) : 0;
    const q = new URLSearchParams({ since: voiceSessionStart.current.toISOString(), live: String(live) });
    const res = await fetch(`/api/ai/command/usage?${q}`);
    if (!res.ok) return null;
    return (await res.json()) as import("@/app/lib/assist/usageCost").CostReport;
  }, [voiceAssistOn, voiceListening]);
  const voiceDictRef = useRef<DictationHandle | null>(null);

  // ── Guided "rename by number" flow (voice) ──
  //   pick: green number badges shown; user says a number.
  //   name: an item is selected/editing; user dictates the new name.
  // (RenameFlow is defined beside the apply layer, which opens it.)
  const [renameFlow, setRenameFlowState] = useState<RenameFlow | null>(null);
  const renameFlowRef = useRef<RenameFlow | null>(null);
  const setRenameFlow = useCallback((f: RenameFlow | null) => { renameFlowRef.current = f; setRenameFlowState(f); }, []);
  // ── Guided "message by number" flow (messageTargets.ts): badges on the
  //    candidates; the user says "n to m labelled X" or "to/from n labelled X".
  const [messageFlow, setMessageFlowState] = useState<MessagePick | null>(null);
  const messageFlowRef = useRef<MessagePick | null>(null);
  const setMessageFlow = useCallback((f: MessagePick | null) => { messageFlowRef.current = f; setMessageFlowState(f); }, []);
  // "move dividers" (dividerFlow.ts): open while the numbers are on the dividers.
  // The numbers are recomputed from the diagram, so they follow each move.
  const [dividerFlow, setDividerFlowState] = useState<DividerFlow | null>(null);
  const dividerFlowRef = useRef<DividerFlow | null>(null);
  // What the flow remembers between answers — a held number, the last move (dividerFlow.ts DividerMemory).
  // Fresh each time the flow opens or closes.
  const dividerMemRef = useRef<DividerMemory>({});
  const setDividerFlow = useCallback((f: DividerFlow | null) => { dividerFlowRef.current = f; dividerMemRef.current = {}; setDividerFlowState(f); }, []);
  const dividerTargets = useMemo(() => (dividerFlow ? collectDividers(data.elements, dividerFlow.order) : null), [dividerFlow, data.elements]);
  // Green ticks every 100px down the lanes' name strips while it is open (Paul, 2026-09-28).
  const onScreenRulers = useMemo(() => (dividerFlow ? dividerRulers(data.elements) : null), [dividerFlow, data.elements]);
  // ── R2: the disambiguation picker. Same numbered-badge mechanism as the
  //    rename and message flows — the point of R2 was never new UI, it was that
  //    a mechanism the product already had was not reached from the one place
  //    that most needed it.
  // "Add template" (Paul, 2026-09-24): the numbered window, and the template
  // currently sitting on the diagram waiting to be kept. The pick is applied
  // for real so it can be SEEN in place; another number replaces it (the
  // diagram it was applied to goes back, then the next goes on — one undo
  // entry however many are tried); only "yes" keeps it.
  const [templateFlow, setTemplateFlowState] = useState<TemplateFlow | null>(null);
  // The template window's scrolling list — "scroll down" moves it (Paul, 2026-09-28).
  const templateScrollRef = useRef<HTMLDivElement | null>(null);
  const templateFlowRef = useRef<TemplateFlow | null>(null);
  const setTemplateFlow = useCallback((f: TemplateFlow | null) => { templateFlowRef.current = f; setTemplateFlowState(f); }, []);
  // Every pick (and every close) takes a new number; a pick whose template
  // arrives after a newer one began — a double click, voice and mouse at once,
  // or Esc while it loaded — is dropped rather than stacked.
  const templatePickSeqRef = useRef(0);
  // Defined with the template window below; reached through refs from the
  // voice runner and the Esc handler, which are defined before them.
  const closeTemplateFlowRef = useRef<(keep: boolean) => string>(() => "");
  const pickTemplateCardRef = useRef<(card: TemplateCard, report: TemplateReport) => Promise<void>>(async () => {});
  const reanchorTemplateRef = useRef<(ref: string, report: TemplateReport) => Promise<void>>(async () => {});
  const [pickFlow, setPickFlowState] = useState<PickFlow | null>(null);
  const pickFlowRef = useRef<PickFlow | null>(null);
  const setPickFlow = useCallback((f: PickFlow | null) => { pickFlowRef.current = f; setPickFlowState(f); }, []);
  const voiceStopRequested = useRef(false);
  // Stable ref to the JSON export (a plain function redefined each render) so
  // the memoised apply layer can call it without churning its deps.
  const exportJsonRef = useRef<(() => void) | null>(null);
  // Voice Assist is always OFF when you open (or switch) a diagram — a live mic
  // should never be silently on when you arrive. Reset + stop on diagram change.
  //
  // Everything of the old diagram ends with it (Paul's ruling, 2026-09-29): the
  // questions, the numbered flows, the queue, anything buffered — and the log,
  // which was about the old diagram. The questions and the buffer go FIRST:
  // stopping the recogniser runs whatever is buffered, and a buffered "yes"
  // must never answer "clear the diagram?" on the way out.
  useEffect(() => {
    setVoiceAssistOn(false);
    pendingConfirmRef.current = null; // a parked "clear the diagram?" never outlives the diagram it was asked on
    pickFlowRef.current = null;       // nor a parked "which one?" — its candidates are on the old diagram
    boundaryLastRef.current = null;   // nor a boundary's follow-up
    setPickFlowState(null);
    setRenameFlow(null);
    setMessageFlow(null);
    setDividerFlow(null);
    setTemplateFlow(null);
    voiceQueueRef.current = [];
    voiceBuffer.current = "";
    voiceWaits.current = 0;
    if (voiceFlushTimer.current) { clearTimeout(voiceFlushTimer.current); voiceFlushTimer.current = null; }
    setVoiceInterim("");
    voiceSwitchSeq.current += 1;      // an AI reply for the old diagram is dropped, silently, when it arrives
    if (voiceIdleTimer.current) { clearTimeout(voiceIdleTimer.current); voiceIdleTimer.current = null; } // nor does its idle clock run on
    voiceDictRef.current?.stop();
    voiceDictRef.current = null;
    setVoiceListening(false);
    setAbraConnecting(false);
    setVoiceLog([]);
  }, [diagramId]);

  // The numbered badges on the canvas — drawn by the Canvas, and saved by the
  // debug recording, from this one value, so what is saved is what was drawn.
  const onScreenBadges = badgesOnScreen(renameFlow, messageFlow, pickFlow, dividerTargets);
  /**
   * Save one state of the diagram into the debug recording, with what was on
   * screen: the selection, the pointer, what "it" means, the numbered badges
   * and the open flow — what a replay of the next command needs. Returns the
   * snapshot's id, or null when the ledger says it is not worth keeping (the
   * same diagram as the last saved state, or past the size limit).
   *
   * A ref reassigned every render (the `runAbraCommandRef` idiom), so the
   * command path reaches this render's values without rebuilding on every edit.
   */
  const saveDebugStateRef = useRef<(state: DiagramData, role: SnapshotRole, entryId: string | null) => string | null>(() => null);
  saveDebugStateRef.current = (state, role, entryId) => {
    const r = captureState(debugLedgerRef.current, state, {
      role, diagramType, colorConfig: diagramColorConfig, displayMode,
      ui: {
        selectedIds: [...selectedIdsRef.current],
        selectedConnectorId: selectedConnectorIdRef.current,
        pointer: pointerWorld.current ? { ...pointerWorld.current } : null,
        voiceLastId: voiceLastId.current,
        badges: onScreenBadges ?? null,
        flow: projectFlow({ template: templateFlow, pick: pickFlow, rename: renameFlow, message: messageFlow, dividers: dividerTargets }),
      },
    });
    debugLedgerRef.current = r.ledger;
    if (!("diagramJson" in r)) {
      if (r.stoppedNow) appendLog({ heard: "", summary: captureStoppedSummary(r.ledger), ok: true });
      return null;
    }
    const id = nanoid();
    setDebugSnapshots((prev) => [...prev, {
      id, entryId, takenAt: Date.now(),
      diagramJson: r.diagramJson,
      elementCount: state.elements.length,
      connectorCount: state.connectors.length,
    }]);
    return id;
  };
  // "Save once when recording starts" (Q1): the bar open with debug on, or the
  // log cleared while recording (a new epoch — clearVoiceLog).
  const [debugEpoch, setDebugEpoch] = useState(0);
  useEffect(() => {
    if (voiceAssistOn && voiceDebugRecording) saveDebugStateRef.current(debugDataRef.current, "start", null);
  }, [voiceAssistOn, voiceDebugRecording, debugEpoch]);


  /**
   * Arm the gold flash: remember where everything was and what it was called,
   * so the effect below can diff once React has re-rendered and outline what
   * changed. A no-op unless the user has flashing switched on.
   *
   * Two callers — the op batch and the guided rename flow — because the rename
   * flow writes labels through its own path and never touches applyAssistOps.
   * That is why renaming flashed nothing at all (Paul, 2026-09-18).
   */
  const armGoldFlash = useCallback((elements: DiagramElement[]) => {
    if (!isGoldFlashOn()) return;
    goldFlashBeforeRef.current = elements.map((e) => ({
      id: e.id, x: e.x, y: e.y, width: e.width, height: e.height, parentId: e.parentId, label: e.label,
      marks: subtypeFingerprint(e as unknown as Record<string, unknown>),
    }));
  }, []);
  /** The debug recording's before-snapshot — the op batch, the template
   *  window's picks and the guided rename all change the diagram, and all are
   *  evidence. Two halves: the boxes the "touched" diff needs, and the diagram
   *  itself, saved as a "before" when the mouse has changed it since the last
   *  saved state (otherwise the last "after" already is this state). */
  const armDebugBefore = useCallback((elements: DiagramElement[]) => {
    if (voiceDebugRecording) {
      debugBeforeRef.current = elements.map((e) => ({
        id: e.id, type: e.type, x: e.x, y: e.y, width: e.width, height: e.height,
        parentId: e.parentId, label: e.label,
        marks: subtypeFingerprint(e as unknown as Record<string, unknown>),
      }));
      // Two applies before a render (a queued command drained in the same
      // tick) share the first one's before-state: the diagram it started from.
      if (!debugArmRef.current) {
        const before = debugDataRef.current;
        debugArmRef.current = { before, beforeShotId: saveDebugStateRef.current(before, "before", null) };
      }
    }
  }, [voiceDebugRecording]);
  // Apply interpreted ops. The work is in app/lib/assist/applyAssistOps.ts, so the
  // test harness can run the SAME code against a headless diagram (L4); what
  // stays here is editor memory ("again") and the display snapshots taken around it.
  const applyAssistOps = useCallback((incoming: AssistOp[]): { ok: boolean; summary: string } => {
    // "again" repeats the last real command (a nudge, a move, an add…).
    let ops = incoming;
    if (ops.length === 1 && ops[0].op === "again") {
      if (!lastAbraOpsRef.current.length) return { ok: false, summary: "nothing to repeat yet" };
      ops = lastAbraOpsRef.current;
    } else if (ops.length && !ops.every((o) => o.op === "undo" || o.op === "again" || o.op === "export")) {
      lastAbraOpsRef.current = ops; // remember for "again" (but not undo/again/export)
    }
    // Gold flashing: remember where everything was, so that once React has
    // re-rendered we can diff and outline whatever this command touched. Taken
    // here rather than asking each of the thirty-odd op handlers to report what
    // it changed — handlers drift, and a new op would silently stop flashing.
    if (batchFlashes(ops)) armGoldFlash(data.elements);
    // The same trick again, for the debug log. Armed UNCONDITIONALLY while
    // recording — `batchFlashes` deliberately skips the ops that change nothing
    // worth outlining, and those are exactly the ones whose effect a person
    // cannot see by looking, so they are the ones the evidence needs most.
    armDebugBefore(data.elements);
    // After the arm, whose size-limit line (if it writes one) must not take
    // them. Cleared on the next microtask in case no line follows after all.
    appliedOpsRef.current = ops;
    queueMicrotask(() => { if (appliedOpsRef.current === ops) appliedOpsRef.current = null; });
    return applyAssistOpsTo(ops, {
      elements: data.elements, connectors: data.connectors, settings: assistSettingsOf(data), riskCatalog, autoConnect,
      actions: {
        addElementGated, updateProperties, updateLabel, addConnector, deleteConnector, reverseConnector, updateConnectorLabel,
        deleteElement, undo, clearDiagram, setEventBoundary, splitPoolEven, splitLaneEven, wrapInPool,
        wrapInSubprocess, wrapInContainer, unwrapSubprocess, addPool, addLaneAt, compressPool, compressLane, expandLane, extendPools,
        swapLane, moveLane, moveElements, elementsMoveEnd, removeSpace, insertSpace, convertTaskSubprocess, moveLaneBoundary, laneBoundaryMoveEnd, updateConnectorEndpoint, movePoolTo,
        swapPools, resizeElement, resizeElementEnd, alignElements,
      },
      ui: { setSelectedElementIds, setSelectedConnectorId, setPickFlow, setRenameFlow, setMessageFlow, setDividerFlow, setGoldFlash },
      refs: { voiceLastId, pointerWorld, selectedIdsRef, selectedConnectorIdRef, nextStepRef, openTemplateWindowRef, exportJsonRef, boundaryLast: boundaryLastRef },
    });
  }, [data.elements, data.connectors, data.poolFontSize, data.laneFontSize, data.connectorFontSize, data.relaxedLayout, riskCatalog, armDebugBefore, armGoldFlash, addElementGated, updateProperties, updateLabel, addConnector, deleteConnector, reverseConnector, updateConnectorLabel, deleteElement, undo, clearDiagram, setEventBoundary, splitPoolEven, splitLaneEven, wrapInPool, wrapInSubprocess, wrapInContainer, unwrapSubprocess, addPool, addLaneAt, compressPool, compressLane, expandLane, extendPools, swapLane, moveLane, moveElements, elementsMoveEnd, removeSpace, insertSpace, convertTaskSubprocess, moveLaneBoundary, laneBoundaryMoveEnd, updateConnectorEndpoint, movePoolTo, swapPools, resizeElement, resizeElementEnd, alignElements, setRenameFlow, setMessageFlow, setPickFlow, setDividerFlow]);

  // Gold flashing, part two: the command has run, React has re-rendered, and
  // `data.elements` is now the after picture. Diff it against the snapshot taken
  // when the batch was armed and hand the result to the overlay.
  //
  // This runs on every element change, but does nothing at all unless a batch
  // armed it — the ref is the gate, and it is cleared immediately so one command
  // flashes once however many times the canvas re-renders afterwards.
  useEffect(() => {
    const snapshot = goldFlashBeforeRef.current;
    if (!snapshot) return;
    goldFlashBeforeRef.current = null;
    const targets = flashTargets(
      snapshot,
      data.elements.map((e) => ({
        id: e.id, x: e.x, y: e.y, width: e.width, height: e.height, parentId: e.parentId, label: e.label,
      marks: subtypeFingerprint(e as unknown as Record<string, unknown>),
      })),
    );
    if (targets.length === 0) return;
    setGoldFlashState((prev) => ({ runId: prev.runId + 1, targets }));
  }, [data.elements]);

  // The debug half of the same diff. Attaches to the LAST log entry, which is
  // the one the command just wrote: `applyGrouped` is followed immediately by a
  // single `log(...)` call, so by the time React has re-rendered with the new
  // elements, the entry to annotate is the one on the end.
  useEffect(() => {
    const before = debugBeforeRef.current;
    if (!before) return;
    debugBeforeRef.current = null;
    const touched = touchedFor(
      before,
      data.elements.map((e) => ({
        id: e.id, type: e.type, x: e.x, y: e.y, width: e.width, height: e.height,
        parentId: e.parentId, label: e.label,
        marks: subtypeFingerprint(e as unknown as Record<string, unknown>),
      })),
    );
    if (touched.length === 0) return;
    setVoiceLog((prev) => (prev.length === 0
      ? prev
      : prev.map((e, i) => (i === prev.length - 1 ? { ...e, touched } : e))));
  }, [data.elements]);

  // The debug recording's "after", once the command has re-rendered. Keyed on
  // the log as well as the diagram: every command writes a line, so this runs
  // for a command that changed nothing too — and clears its arm, rather than
  // leaving it to catch the next mouse drag as if the command had done it. The
  // entry is the last one, by the same rule as "touched" above.
  useEffect(() => {
    const armed = debugArmRef.current;
    if (!armed) return;
    debugArmRef.current = null;
    const lastEntryId = voiceLog.length ? voiceLog[voiceLog.length - 1].id : null;
    const { linkBefore, entrySnapshot } = settleArm(armed, data, lastEntryId, (entryId) => saveDebugStateRef.current(data, "after", entryId));
    if (linkBefore) setDebugSnapshots((prev) => prev.map((s) => (s.id === linkBefore.snapshotId ? { ...s, entryId: linkBefore.entryId } : s)));
    if (entrySnapshot) setVoiceLog((prev) => prev.map((e) => (e.id === entrySnapshot.entryId ? { ...e, snapshotId: entrySnapshot.snapshotId } : e)));
  }, [data, voiceLog]);

  /**
   * The bar's "clear" starts the recording afresh. The saved states belong to
   * the lines being cleared: kept, they would be states no line points at —
   * invisible in the viewer, yet counted against the size limit — and the
   * ledger would still hold the last "after", so the next command would get
   * no "before" of its own. The new recording's "start" is saved by the start
   * effect, which the new epoch wakes.
   */
  const clearVoiceLog = useCallback(() => {
    setVoiceLog([]);
    setDebugSnapshots([]);
    debugLedgerRef.current = newCaptureLedger();
    debugArmRef.current = null;
    debugBeforeRef.current = null;
    setDebugEpoch((n) => n + 1);
  }, []);

  /** Record what Paul thought of one command. */
  const annotateCommand = useCallback((id: string, patch: { note?: string; verdict?: CommandVerdict }) => {
    setVoiceLog((prev) => prev.map((e) => (e.id === id ? { ...e, ...patch } : e)));
  }, []);

  /**
   * 📷 — "mark this moment": save the diagram as it is now, as JSON, with what
   * is on screen (the numbered badges, the selection).
   *
   * NO PICTURE. On 24 Sep Paul decided a snapshot captures the diagram JSON
   * *and* a PNG; on 26 Sep he reversed it — "Make the snapshots in Voice Assist
   * JSON, not SVG. These can be better used for diagnosis." The JSON had been
   * in every snapshot all along, behind a button that said "take a picture";
   * the pictures were 78–89 % of every file and could not be replayed. The one
   * thing only a picture showed, the numbered badges, is saved as data and
   * redrawn by the viewer's canvas.
   *
   * Recording also saves the diagram around every command on its own (Q1); this
   * saves it regardless, because the badges or the selection may be the point.
   */
  const takeDebugSnapshot = useCallback((entryId: string | null) => {
    const id = saveDebugStateRef.current(data, "marked", entryId);
    if (id && entryId) setVoiceLog((prev) => prev.map((e) => (e.id === entryId ? { ...e, snapshotId: id } : e)));
  }, [data]);

  /**
   * The session, built once and used for both destinations.
   *
   * Save-to-disk and save-to-database take THE SAME PAYLOAD — the POST route
   * accepts exactly what the download writes — so a downloaded file can be
   * posted back and the two shapes cannot drift apart.
   */
  const buildDebugSession = useCallback((savedAt: number) =>
    buildDebugSessionFile({
      title: `Voice Assist — ${diagramName || "diagram"}`,
      diagramId,
      diagramName,
      entries: voiceLog,
      snapshots: debugSnapshots,
      savedAt,
      appVersion: PRODUCT_VERSION,
    }), [voiceLog, debugSnapshots, diagramName, diagramId]);

  const [debugSaveState, setDebugSaveState] = useState<"idle" | "saving" | "saved" | "error">("idle");
  const saveDebugSession = useCallback(async () => {
    setDebugSaveState("saving");
    try {
      const res = await fetch("/api/admin/voice-debug/sessions", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(buildDebugSession(Date.now())),
      });
      setDebugSaveState(res.ok ? "saved" : "error");
    } catch {
      setDebugSaveState("error");
    }
    // Back to "Save" after a moment, so a second save later in the session is
    // obviously available rather than looking already done.
    setTimeout(() => setDebugSaveState("idle"), 4000);
  }, [buildDebugSession]);

  /** The whole session as one file: commands, verdicts, comments, snapshots. */
  const downloadDebugSession = useCallback(() => {
    const savedAt = Date.now();
    const blob = new Blob([serialiseDebugSession(buildDebugSession(savedAt))], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = debugSessionFilename(diagramName, new Date(savedAt).toISOString());
    a.click();
    URL.revokeObjectURL(url);
  }, [buildDebugSession, diagramName]);

  // Cancel the guided rename flow and clear any badge/edit state.
  const cancelRenameFlow = useCallback((reason?: string) => {
    setRenameFlow(null);
    cancelLabelEdit();
    if (reason) appendLog({ heard: "", summary: reason, ok: true });
  }, [setRenameFlow, cancelLabelEdit, appendLog]);

  // Apply a dictated name to the picked element/connector, then STAY in the loop
  // (#3): re-number the same type so the user can keep renaming until "stop"/Esc.
  const applyRenameName = useCallback((target: { id: string; kind: "element" | "connector" }, name: string, itemType: RenameType, single = false) => {
    // Item names start with a capital (Paul, 2026-09-17). Dictation returns a
    // lower-case sentence fragment, which then sits on the diagram looking like
    // a typo beside every name that was typed. First word only — a process step
    // is a phrase, and title case would give "Send To Customer For Approval".
    // "clear" / "no label" / "blank" — a connector or message left with NO label
    // (Paul, 2026-10-01). An empty name still means cancel; this is the way to ask
    // for empty on purpose. Elements keep their names: a task with none is not
    // something to do by accident, so it says so and waits for a name.
    const clearing = isClearLabelWord(name);
    if (clearing && target.kind !== "connector") {
      cancelLabelEdit();
      appendLog({ heard: name.trim(), summary: "a name can’t be cleared here — say the new name", ok: false });
      return;
    }
    // A pool, lane or sub-lane takes EVERY word capitalised (Paul, 2026-10-01); everything else, the first word only.
    const targetType = target.kind === "element" ? data.elements.find((e) => e.id === target.id)?.type : undefined;
    const spoken = name.trim().replace(/[.,!?;:]+$/g, "");
    const clean = clearing ? "" : targetType && isFullyCapitalised(targetType) ? titleCaseName(spoken) : capitaliseFirstWord(spoken);
    if (!clean && !clearing) { cancelRenameFlow("rename cancelled (empty name)"); return; }
    // The guided flow writes the label itself, so it has to arm the flash
    // itself too — applyAssistOps is never involved. The debug recording
    // likewise: a rename is a command that changed the diagram.
    armGoldFlash(data.elements);
    armDebugBefore(data.elements);
    if (target.kind === "element") updateLabel(target.id, clean);
    else updateConnectorLabel(target.id, clean);
    cancelLabelEdit();
    // Selection protocol (Paul, 2026-09-15): a rename by voice does not leave
    // the item selected — the badges are the cue, not a highlight.
    setSelectedElementIds(new Set());
    setSelectedConnectorId(null);
    if (single) {
      // "label selected": one item, no pick loop afterwards.
      setRenameFlow(null);
      appendLog({
        heard: clearing ? name.trim() : clean,
        summary: clearing ? "cleared the connector’s label" : target.kind === "connector" ? `labelled the connector “${clean}”` : `labelled “${clean}”`,
        ok: true,
      });
      return;
    }
    // The edit above has only been DISPATCHED: `data` in this closure is still the diagram from before
    // it, so a list built from `data` keeps the OLD name — and the phone's numbered list prints each
    // name, so the renamed task still showed its old one (Paul, 2026-10-01). Build the list from the
    // diagram as it is about to be.
    const els = target.kind === "element" ? data.elements.map((e) => (e.id === target.id ? { ...e, label: clean } : e)) : data.elements;
    const conns = target.kind === "connector" ? data.connectors.map((c) => (c.id === target.id ? { ...c, label: clean } : c)) : data.connectors;
    const targets = collectRenameTargets(els, conns, itemType);
    if (targets.length > 0) setRenameFlow({ phase: "pick", itemType, targets });
    else setRenameFlow(null);
    appendLog({ heard: clearing ? name.trim() : clean, summary: clearing ? "cleared the label — pick another or say “done”" : `renamed to “${clean}” — pick another or say “done”`, ok: true });
  }, [updateLabel, updateConnectorLabel, cancelLabelEdit, setRenameFlow, cancelRenameFlow, armDebugBefore, appendLog, data.elements, data.connectors]);

  // Handle one utterance while the guided rename flow is active.
  const handleRenameUtterance = useCallback((text: string) => {
    const flow = renameFlowRef.current;
    if (!flow) return;
    // "3 F I N A N C E" names it Finance — the spelled escape hatch the
    // command grammar has too (spelledWord.ts).
    const t = joinSpelledLetters(text.trim());
    const low = t.toLowerCase().replace(/[.,!?;:]+$/g, "").trim();
    // "done"/"cancel"/Esc-words end the rename loop (mic stays on); a bare
    // "stop" never reaches here — it stops the mic (stopWords.ts).
    if (isFlowEndWord(low)) { cancelRenameFlow("rename finished"); return; }
    // "Undo" inside a numbered pick meant "get me out of this", and it was
    // answered with "say the number of the item to rename" — three times in a
    // row, in Paul's log (2026-09-21), which is the feature arguing with
    // someone trying to leave. It now does BOTH: drop the pick, then undo.
    // The undo changes the diagram, so the debug recording is armed first: its
    // "after" lands on its own line, not later as a "before" the mouse caused.
    if (/^undo\b/.test(low)) {
      armDebugBefore(elementsRef.current);
      cancelRenameFlow("rename cancelled");
      undo();
      appendLog({ heard: t, summary: "undid the last change", ok: true });
      return;
    }
    if (flow.phase === "pick") {
      // Leading number (digit, number-word, or a known mishearing of one)
      // selects a badge; trailing text is the name. `leadingSpokenNumber`
      // absorbs the recogniser substituting "lane" for "one" — a bias we
      // create ourselves by boosting `lane` (spokenNumber.ts).
      // A number is due here, so a leading "the" that is not followed by a number can only have been
      // "one" (the recogniser's habit — spokenNumber.ts restoreLostOneNumber).
      const picked = leadingSpokenNumber(restoreLostOneNumber(t));
      if (!picked) { appendLog({ heard: t, summary: "say the number of the item to rename", ok: false }); return; }
      const n = picked.n;
      const target = flow.targets.find((x) => x.n === n);
      if (!target) { appendLog({ heard: t, summary: `there’s no number ${n}`, ok: false }); return; }
      // "select <type>" (Paul, 2026-10-01): the pick SELECTS the item and the flow ends — nothing is renamed, no
      // edit box opens. The item stays selected, so "move label up" or "rename this to …" can follow.
      if (flow.purpose === "select") {
        if (target.kind === "element") { setSelectedConnectorId(null); setSelectedElementIds(new Set([target.id])); voiceLastId.current = target.id; }
        else { setSelectedElementIds(new Set()); setSelectedConnectorId(target.id); }
        setRenameFlow(null);
        appendLog({ heard: t, summary: `selected ${target.label ? `“${target.label}”` : `number ${n}`}`, ok: true });
        return;
      }
      // Select + enter edit mode (+ zoom for elements) so the change is visible.
      if (target.kind === "element") { setSelectedConnectorId(null); setSelectedElementIds(new Set([target.id])); beginLabelEdit(target.id); }
      else { setSelectedElementIds(new Set()); setSelectedConnectorId(target.id); }
      const trailing = picked.rest;
      // A rename target is an element or a connector — never a divider (dividerFlow.ts has its own flow).
      const renameKind: "element" | "connector" = target.kind === "element" ? "element" : "connector";
      if (trailing) { applyRenameName({ ...target, kind: renameKind }, trailing, flow.itemType); }         // "14 Approve Invoice" in one breath
      else { setRenameFlow({ phase: "name", itemType: flow.itemType, targetId: target.id, kind: renameKind }); } // wait for the name
      return;
    }
    // phase "name" — the whole utterance is the new name.
    applyRenameName({ id: flow.targetId, kind: flow.kind }, t, flow.itemType, flow.single === true);
  }, [applyRenameName, cancelRenameFlow, setRenameFlow, beginLabelEdit, appendLog, armDebugBefore]);
  const handleRenameUtteranceRef = useRef(handleRenameUtterance);
  handleRenameUtteranceRef.current = handleRenameUtterance;

  // One spoken command = ONE undo entry, however many reducer helpers it fans
  // out into (historyGroup.ts). "Undo that" used to revert only the last of them.
  const applyGrouped = useCallback((ops: AssistOp[]) => {
    // Any other command ends a boundary command's follow-up (boundaryFollowUp.ts).
    if (!(ops.length === 1 && ops[0].op === "movePoolBoundary" && !ops[0].overContent)) boundaryLastRef.current = null;
    beginHistoryGroup();
    try { return applyAssistOps(ops); } finally { endHistoryGroup(); }
  }, [applyAssistOps, beginHistoryGroup, endHistoryGroup]);

  // The answer to a numbered message pick: "3 to 7 labelled Order Placed" /
  // "to 2 labelled X" / "from 2 labelled X" — or "done" to walk away.
  const handleMessageUtterance = useCallback((text: string) => {
    const flow = messageFlowRef.current;
    if (!flow) return;
    const t = text.trim();
    const log = (summary: string, ok: boolean) => appendLog({ heard: t, summary, ok });
    if (isFlowEndWord(t)) { setMessageFlow(null); log("message cancelled", true); return; }
    const a = parseMessageAnswer(t, flow.mode);
    if (!a) {
      // Offer only the forms that can work — a receive-only anchor never "to".
      const forms = flow.mode === "pair" ? ["“<n> to <m> labelled <text>”"]
        : [flow.dirs.to ? "“to <n> labelled <text>”" : "", flow.dirs.from ? "“from <n> labelled <text>”" : ""].filter(Boolean);
      log(`say ${forms.join(" or ")} — or “done”`, false);
      return;
    }
    // A refused answer (no such badge, or said backwards — "12 to 1" where 12
    // only receives) keeps the numbers up so it can simply be said again.
    const ends = resolveMessageAnswer(flow, a, elementsRef.current, connectorsRef.current);
    if ("error" in ends) { log(ends.error, false); return; }
    const { fromId, toId } = ends;
    setMessageFlow(null);
    const r = applyGrouped([{ op: "addMessage", fromRef: ID_REF_PREFIX + fromId, toRef: ID_REF_PREFIX + toId, ...(a.label ? { label: a.label } : {}) }]);
    log(r.summary, r.ok);
  }, [applyGrouped, setMessageFlow, appendLog]);
  const handleMessageUtteranceRef = useRef(handleMessageUtterance);
  handleMessageUtteranceRef.current = handleMessageUtterance;

  // The answer while "move dividers" is open: "2 up 100 pixels", "two down 2
  // tasks", "3 up" — or "done". Each answer runs the boundary command on the
  // band below that divider (its top IS the line) — through whatever is in the
  // way, down to what the names allow (Paul, 2026-09-28) — and the numbers stay
  // up for the next nudge. An answer said in two halves is still one answer:
  // "one" … "down two tasks"; "one down" … "fifty pixels" (dividerFlow.ts).
  const handleDividerUtterance = useCallback((text: string) => {
    const t = text.trim();
    const log = (summary: string, ok: boolean) => appendLog({ heard: t, summary, ok });
    if (isFlowEndWord(t)) { setDividerFlow(null); log("dividers closed", true); return; }
    const targets = collectDividers(elementsRef.current, dividerFlowRef.current?.order);
    const mem = dividerMemRef.current;
    const u = readDividerUtterance(t, targets, mem);
    if (!u || u.kind === "miss") { log(explainDividerMiss(t, targets), false); return; }
    if (u.kind === "hold") { mem.pendingN = u.n; mem.pendingPx = undefined; log(`${u.n} — now “up …” or “down …”`, true); return; }
    if (u.kind === "askWay") { mem.pendingPx = u.px; log(`${u.n}, ${u.px} pixels — up or down?`, true); return; }
    const more = (ok: boolean) => (ok ? " — another, or “done”" : "");
    if (u.kind === "adjust") {
      const so = mem.last!.moved;
      const op = adjustOp(u, so);
      if (!op) { log(`${u.target.n} has moved ${u.total}px ${u.direction} already${more(true)}`, true); return; }
      const r = applyGrouped([op]);
      const m = movedPx(r.summary);
      const total = so + (op.op === "movePoolBoundary" && op.direction === u.direction ? m : -m);
      mem.last = { id: u.target.id, n: u.target.n, direction: u.direction, moved: total };
      log(`${u.target.n} → ${dividerReply(r.summary, u.target.n)} (${Math.round(total)}px ${u.direction} in all)${more(r.ok)}`, r.ok);
      return;
    }
    const a = u.answer;
    mem.pendingN = undefined;
    mem.pendingPx = undefined;
    const r = applyGrouped([dividerOp(a)]);
    mem.last = { id: a.target.id, n: a.target.n, direction: a.direction, moved: r.ok ? movedPx(r.summary) : 0 };
    log(`${a.target.n} → ${dividerReply(r.summary, a.target.n)}${more(r.ok)}`, r.ok);
  }, [applyGrouped, setDividerFlow, appendLog]);
  const handleDividerUtteranceRef = useRef(handleDividerUtterance);
  handleDividerUtteranceRef.current = handleDividerUtterance;

  // Interpret a raw command (deterministic first; AI fallback added in Stage 4).
  // `fromQueue`: the drain effect is running the queue's head, whose turn it is.
  const runVoiceCommand = useCallback(async (text: string, fromQueue = false) => {
    const heard = text.trim();
    if (!heard) return;
    // `appendLog` stamps `at` on every entry and carries the ops just applied.
    const log = appendLog;
    // A typed "stop" means the same as a spoken one: the mic, and anything parked, ends.
    if (isMicStopWord(heard)) {
      // "stop" is the brake — it must never queue behind an in-flight call,
      // and it throws away anything already parked. Paul made the word
      // unambiguous for exactly this reason (49b13eb1).
      voiceQueueRef.current = [];
      stopAbraListeningRef.current();
      log({ heard, summary: "stopped listening", ok: true });
      return;
    }
    // Everything else queues rather than races, so commands apply in the order
    // they were spoken, each against the state the one before it left behind.
    // That includes a queue still draining after the call has finished: the
    // drain waits for a render, and a newcomer must not jump it.
    if (!fromQueue && (voiceBusyRef.current || voiceQueueRef.current.length > 0)) {
      voiceQueueRef.current.push(heard);
      log({ heard, summary: "waiting for the previous command…", ok: true });
      return;
    }
    // A flow word ("done", "cancel", "stop rename") with nothing open to close
    // is what the spoken path already says it is — nothing to do — rather than
    // a metered AI call to accomplish nothing (2026-09-29).
    if (isFlowEndWord(heard) && !(renameFlowRef.current || messageFlowRef.current || dividerFlowRef.current
      || templateFlowRef.current || pickFlowRef.current || pendingConfirmRef.current)) {
      log({ heard, summary: "cleared — listening for the next command", ok: true });
      return;
    }
    // While a guided pick is active, every utterance feeds it (a number, a
    // name, or "done") — never the general command parser.
    //
    // One exception: switching gold flashing on or off. It edits nothing, so it
    // cannot disturb the pick, and the pick is exactly where you notice you
    // wanted it on (Paul, 2026-09-18). Without this the words are taken as the
    // new name for whichever item you had picked.
    if (renameFlowRef.current || messageFlowRef.current || dividerFlowRef.current) {
      const toggle = parseCommand(heard);
      if (toggle && toggle.length === 1 && toggle[0].op === "goldFlash") {
        const r = applyGrouped(toggle);
        log({ heard, summary: r.summary, ok: r.ok });
        return;
      }
    }
    // "move dividers" is open. An answer — or half of one, or "done" — is its
    // to read (a bare "one" was taken as "accept the suggestion", 2026-09-28);
    // a whole new command closes it and runs — the numbers are never a trap
    // (as the pick, pickInterrupt.ts).
    if (dividerFlowRef.current) {
      const answer = readDividerUtterance(heard, collectDividers(elementsRef.current, dividerFlowRef.current.order), dividerMemRef.current);
      if (!answer && !isFlowEndWord(heard) && parseCommand(heard)) setDividerFlow(null);
      else { handleDividerUtteranceRef.current(heard); return; }
    }
    if (templateFlowRef.current) {
      const flow = templateFlowRef.current;
      const answer = parseTemplateAnswer(heard, flow.cards, !!flow.provisional);
      if (!answer) { log({ heard, summary: "say a number, or “cancel”", ok: false }); return; }
      if (answer.kind === "cancel" || answer.kind === "confirm") {
        log({ heard, summary: closeTemplateFlowRef.current(answer.kind === "confirm"), ok: true });
        return;
      }
      if (answer.kind === "before") { log({ heard, summary: TEMPLATE_BEFORE_REFUSAL, ok: false }); return; }
      if (answer.kind === "scroll") {
        const list = templateScrollRef.current;
        if (!list) { log({ heard, summary: "the template window isn't showing its list yet — say a number", ok: false }); return; }
        const target = templateScrollTarget(answer.to, list);
        if ("top" in target) list.scrollTo({ top: target.top, behavior: "smooth" });
        log({ heard, summary: templateScrollReply(answer.to, target), ok: true });
        return;
      }
      // A number shows that one instead of whatever is showing now; "after X"
      // moves the window (and what is showing) to X. Each reports in the same
      // tick as its change, so the debug recording's "touched" lands on it.
      const report: TemplateReport = (r) => log({ heard, summary: r.summary, ok: r.ok });
      if (answer.kind === "anchor") await reanchorTemplateRef.current(answer.ref, report);
      else await pickTemplateCardRef.current(answer.card, report);
      return;
    }
    // A delete's question ("which tasks to delete?") takes several numbers at once —
    // "three, seven, eight and nine" — or "all", or one name. Each chosen one is a delete
    // by #id: reference; "all" asks first (one word from a mis-hear).
    const answerDeleteMany = (said: string, flow: PickFlow) => {
      const list = parseNumberList(said, flow.targets.length);
      if (list?.kind === "out-of-range") { log({ heard: said, summary: `there is no number ${list.numbers.join(", ")} — say numbers from 1 to ${flow.targets.length}`, ok: false }); return; }
      const byName = list ? null : parsePickAnswer(said, flow);
      if (!list && !byName) { log({ heard: said, summary: flow.prompt, ok: false }); return; }
      const picked = byName ? [byName] : list!.kind === "all" ? flow.targets : flow.targets.filter((t) => list!.kind === "numbers" && list!.numbers.includes(t.n));
      const delOps = picked.map((t) => ({ op: "delete", ref: `${ID_REF_PREFIX}${t.id}` }) as AssistOp);
      setPickFlow(null);
      const ask = list?.kind === "all" && picked.length > 1
        ? { what: `delete all ${picked.length} ${flow.noun ?? "of them"}` }
        : needsConfirmation(delOps, data.elements, voiceLastId.current, []);
      if (ask) {
        pendingConfirmRef.current = { ops: delOps, what: ask.what, viaAi: false };
        log({ heard: said, summary: `${ask.what}? — say “yes” to confirm`, ok: true });
        return;
      }
      const r = applyGrouped(delOps);
      log({ heard: said, summary: `${picked.map((t) => t.n).join(", ")} → ${r.summary}`, ok: r.ok });
    };
    // A whole new command while the numbers are up closes the question and
    // runs (pickInterrupt.ts) — it used to be read as a wrong answer.
    if (pickFlowRef.current && interruptsPick(heard, pickFlowRef.current)) setPickFlow(null);
    if (pickFlowRef.current) {
      const flow = pickFlowRef.current;
      if (isFlowEndWord(heard)) {
        setPickFlow(null);
        log({ heard, summary: "cancelled", ok: true });
        return;
      }
      if (flow.many) { answerDeleteMany(heard, flow); return; }
      const chosen = parsePickAnswer(heard, flow);
      if (!chosen) { log({ heard, summary: flow.prompt, ok: false }); return; }
      setPickFlow(null);
      // Re-run the PARKED command with the choice substituted as an #id:
      // reference, so it goes back through the ordinary path rather than a
      // second one that could behave differently.
      const r = applyGrouped(substituteRef(flow.ops, flow.ref, chosen.id));
      log({ heard, summary: `${chosen.n} → ${r.summary}`, ok: r.ok });
      return;
    }
    if (renameFlowRef.current) { handleRenameUtteranceRef.current(heard); return; }
    if (messageFlowRef.current) { handleMessageUtteranceRef.current(heard); return; }

    // A destructive command parked by the previous utterance — this one answers it.
    if (pendingConfirmRef.current) {
      const pending = pendingConfirmRef.current;
      pendingConfirmRef.current = null;
      const answer = parseConfirmation(heard);
      if (answer === "yes") {
        const r = applyGrouped(pending.ops);
        log({ heard, summary: `confirmed → ${r.summary}`, ok: r.ok, viaAi: pending.viaAi });
        return;
      }
      log({ heard, summary: `cancelled — did not ${pending.what}`, ok: true, viaAi: pending.viaAi });
      if (answer === "no") return;
      // Anything else is a new command: fall through with the old one dropped.
    }

    // Apply now — or, when the command would remove more than one thing, park
    // it and ask (confirm.ts). Undo would recover a mis-heard "clear the
    // diagram", but nobody should have to know that.
    const applyOrAsk = (rawOps: AssistOp[], viaAi: boolean, prefix = "") => {
      // A SURROUND ALWAYS MAKES A NEW POOL (Paul, 2026-09-19). The deterministic
      // grammar already does; the AI does not, and keeps canonicalising a
      // surround it did not quite hear — "Selected with a pool" — into "put a
      // pool around everything", which grows an existing pool and re-homes the
      // diagram instead. When the words the user actually said name the
      // selection, the whole-diagram wrap is not what they asked for, whatever
      // the model returned.
      const ops = rawOps.map((op) =>
        op.op === "wrapInPool" && /\b(?:selected|selection|these|those|highlighted)\b/i.test(heard)
          ? { op: "wrapInContainer", container: "pool" as const, ...(op.label ? { label: op.label } : {}) } as AssistOp
          : op,
      );
      const ask = needsConfirmation(ops, data.elements, voiceLastId.current, selectedIdsRef.current, { all: data.connectors, selectedId: selectedConnectorIdRef.current });
      if (ask) {
        // PIN THE ANSWER TO WHAT WAS ASKED. The question names one element; the
        // "yes" arrives an utterance later, by which time "selected" or "one"
        // may resolve to something else or to nothing at all — five lines of
        // Paul's log, 2026-09-23, are `Yes.` → `confirmed → which sub-lane?`.
        // Substituting the id is the same trick the picker uses (R2), so the
        // re-run goes back through the ordinary path.
        const pinned = ask.targetId && ask.ref ? substituteRef(ops, ask.ref, ask.targetId) : ops;
        pendingConfirmRef.current = { ops: pinned, what: ask.what, viaAi };
        log({ heard, summary: `${prefix}${ask.what}? — say “yes” to confirm`, ok: true, viaAi });
        return;
      }
      const r = applyGrouped(ops);
      log({ heard, summary: `${prefix}${r.summary}`, ok: r.ok, viaAi });
    };

    const ops = parseCommand(heard);
    if (ops) { applyOrAsk(ops, false); return; }
    // A boundary command's follow-up (Paul, 2026-09-28: refused with "say “up by
    // 98”", he said "sixty pixels" — and neither parsed). Only what parses as
    // nothing else, so it never shadows a command; the AI never sees it.
    if (boundaryLastRef.current) {
      const f = readBoundaryFollowUp(heard, boundaryLastRef.current);
      if (f) {
        if ("reply" in f) { log({ heard, summary: f.reply, ok: true }); return; }
        const r = applyGrouped([f.op]);
        const mem = boundaryLastRef.current;
        log({ heard, summary: `${r.summary}${f.inAll && r.ok && mem ? ` (${mem.moved}px ${mem.direction} in all)` : ""}`, ok: r.ok });
        return;
      }
    }
    // Deterministic parser didn't recognise it → AI fallback (metered).
    voiceBusyRef.current = true;
    setVoiceBusy(true);
    const stopSeqAtStart = voiceStopSeq.current;
    const switchSeqAtStart = voiceSwitchSeq.current;
    const stoppedSince = () => voiceStopSeq.current !== stopSeqAtStart;
    const switchedSince = () => voiceSwitchSeq.current !== switchSeqAtStart;
    try {
      const res = await fetch("/api/ai/command", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ instruction: heard, state: { elements: data.elements, connectors: data.connectors }, selectedIds: selectedIdsRef.current }),
      });
      if (switchedSince()) return;
      if (stoppedSince()) { log({ heard, summary: "ignored — you said stop", ok: false, viaAi: true }); return; }
      if (!res.ok) { log({ heard, summary: "didn’t understand that", ok: false, viaAi: true }); return; }
      const j = await res.json();
      if (switchedSince()) return;
      if (stoppedSince()) { log({ heard, summary: "ignored — you said stop", ok: false, viaAi: true }); return; }
      // Prefer the AI's CANONICAL rewrite re-parsed deterministically (fixes
      // mis-hears + guarantees a valid, documented command); fall back to ops.
      const canonical = typeof j.canonical === "string" ? j.canonical.trim() : "";
      const canonicalOps = canonical ? parseCommand(canonical) : null;
      // The canonical is SHOWN to the user, so it has to be in their
      // vocabulary. The model answers with ids because we gave it ids, and the
      // log printed them verbatim — "connect qruut4v9 to ksjm25kj" (Paul,
      // 2026-09-21). The command was right; the sentence describing it was not.
      // The AI never invents a rename (aiGuards.ts) — on either path below.
      if (canonicalOps && aiInventedRename(heard, canonicalOps)) { log({ heard, summary: INVENTED_RENAME_REFUSAL, ok: false, viaAi: true }); return; }
      if (canonicalOps) { applyOrAsk(canonicalOps, true, `“${humaniseIds(canonical, data.elements)}” → `); return; }
      const aiOps = validateOps(j.ops);
      if (aiOps.length === 0) {
        // The command was often understood perfectly — it named something that
        // is not there. "Add a task before review", with no Review on the
        // diagram, sent the user off to rephrase a sentence that was fine
        // (Paul, 2026-09-21). Name the missing thing instead, when we can.
        log({ heard, summary: notUnderstoodMessage(heard, data.elements), ok: false, viaAi: true });
        return;
      }
      if (aiInventedRename(heard, aiOps)) { log({ heard, summary: INVENTED_RENAME_REFUSAL, ok: false, viaAi: true }); return; }
      applyOrAsk(aiOps, true);
    } catch {
      log({ heard, summary: "command service unavailable", ok: false, viaAi: true });
    } finally {
      voiceBusyRef.current = false;
      setVoiceBusy(false);
      // Not the next command itself: nothing has rendered since this call's
      // changes, so it would resolve its names against the diagram from before
      // the call, and the debug recording would fold both into one "after".
      if (voiceQueueRef.current.length > 0) setVoiceDrainTick((n) => n + 1);
    }
  }, [applyGrouped, appendLog, data.elements, data.connectors]);
  // Keep a stable ref so the mic's onText callback always calls the latest.
  const runAbraCommandRef = useRef(runVoiceCommand);
  runAbraCommandRef.current = runVoiceCommand;
  // B4's drain: one queued command per render. Through the REF, not a
  // closure: the render that woke this rebuilt runVoiceCommand over the NEW
  // diagram, and the queued command must see that, not the diagram as it was
  // when it was spoken. Declared after the debug recording's "after" effect,
  // so the command before is settled — its own "after", on its own line —
  // before this one arms.
  useEffect(() => {
    if (voiceBusyRef.current) return;
    const next = voiceQueueRef.current.shift();
    if (next !== undefined) void runAbraCommandRef.current(next, true);
    // Handled on the spot (no AI call), so no call will finish to wake the
    // next: wake it for the render that follows this one.
    if (!voiceBusyRef.current && voiceQueueRef.current.length > 0) setVoiceDrainTick((n) => n + 1);
  }, [voiceDrainTick]);
  exportJsonRef.current = () => { void handleExportJson(); };

  // Voice comes in as fragments (Deepgram finalises on every pause), so ONE
  // spoken command arrives as several onText calls. Buffer the fragments and
  // interpret the whole sentence after a short silence, so "rename the pool …
  // to … My Company" is treated as a single command.
  const voiceBuffer = useRef("");
  const voiceFlushTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const voiceWaits = useRef(0);           // how many times we've held an incomplete command
  // The numbers live in `assist/fragmentBuffer.ts` (2026-09-24) so the live
  // path and a replayed clip cannot disagree about how long to wait.
  const ABRA_SILENCE_MS = FRAGMENT_SILENCE_MS;
  const ABRA_CONTINUE_MS = FRAGMENT_CONTINUE_MS;
  const ABRA_MAX_WAITS = FRAGMENT_MAX_WAITS;
  // Auto-close after 2 min of no voice — an open Deepgram stream is billed by
  // duration, so an idle mic keeps costing money. Reset on every voice fragment.
  const voiceIdleTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const ABRA_IDLE_MS = 120000;
  const flushVoiceBuffer = useCallback((force = false) => {
    if (voiceFlushTimer.current) { clearTimeout(voiceFlushTimer.current); voiceFlushTimer.current = null; }
    const cmd = voiceBuffer.current.trim();
    // A split command ("rename Task 8 to" … pause … "Approve") — keep the buffer
    // and wait a bit longer for the continuation rather than running the half.
    if (!force && cmd && isIncompleteCommand(cmd) && voiceWaits.current < ABRA_MAX_WAITS) {
      voiceWaits.current += 1;
      voiceFlushTimer.current = setTimeout(() => flushVoiceBuffer(), ABRA_CONTINUE_MS);
      return;
    }
    voiceWaits.current = 0;
    voiceBuffer.current = "";
    setVoiceInterim("");
    if (cmd) {
      const nothingOpen = !(renameFlowRef.current || messageFlowRef.current || dividerFlowRef.current
        || templateFlowRef.current || pickFlowRef.current || pendingConfirmRef.current);
      const fixed = nothingOpen ? host.repairCommandRef?.current?.(cmd) : null;
      if (fixed && fixed.text !== cmd) {
        appendLog({ heard: cmd, summary: fixed.note ?? `read as “${fixed.text}”`, ok: true });
        void runAbraCommandRef.current(fixed.text);
      } else void runAbraCommandRef.current(cmd);
    }
  }, []);

  const stopAbraListening = useCallback(() => {
    voiceStopRequested.current = true;
    voiceStopSeq.current += 1;       // an AI reply still on its way is dropped when it arrives
    voiceQueueRef.current = [];      // nothing waiting runs after a stop, however it was stopped
    if (voiceIdleTimer.current) { clearTimeout(voiceIdleTimer.current); voiceIdleTimer.current = null; }
    // A stop ends every QUESTION first (Paul's ruling, 2026-09-29): a waiting
    // "clear the diagram?" or "which one?" — and whatever was buffered as its
    // answer — before the recogniser stops, because stopping it runs what is
    // buffered, and a buffered "yes" must never confirm on the way out.
    // (The template window's "keep it?" counts too — the window itself stays
    // open for the mouse, but a buffered "yes" must not keep a template.)
    const answering = !!(pendingConfirmRef.current || pickFlowRef.current || templateFlowRef.current);
    pendingConfirmRef.current = null;
    setPickFlow(null);
    if (answering) {
      voiceBuffer.current = "";
      voiceWaits.current = 0;
      if (voiceFlushTimer.current) { clearTimeout(voiceFlushTimer.current); voiceFlushTimer.current = null; }
      setVoiceInterim("");
    }
    voiceDictRef.current?.stop();
    voiceDictRef.current = null;
    setVoiceListening(false);
    setAbraConnecting(false);
    // The numbered flows end with the mic too (a name still buffered for an open rename is read first).
    setRenameFlow(null);
    setMessageFlow(null);
    setDividerFlow(null);
    flushVoiceBuffer(true); // apply anything still buffered (force — no more is coming)
  }, [flushVoiceBuffer, setRenameFlow, setMessageFlow, setDividerFlow, setPickFlow]);
  stopAbraListeningRef.current = stopAbraListening;

  // (Re)arm the 2-minute idle auto-close; called on every voice fragment.
  const bumpAbraIdle = useCallback(() => {
    if (voiceIdleTimer.current) clearTimeout(voiceIdleTimer.current);
    voiceIdleTimer.current = setTimeout(() => {
      appendLog({ heard: "", summary: "Voice Assist closed — 2 minutes idle", ok: true });
      stopAbraListening();
    }, ABRA_IDLE_MS);
  }, [stopAbraListening, appendLog]);

  const toggleAbraListening = useCallback(async () => {
    if (voiceListening || voiceDictRef.current) { stopAbraListening(); return; }
    voiceStopRequested.current = false;
    voiceBuffer.current = "";
    voiceMicOpenedAt.current = Date.now(); // the open session has no usage row yet — Cost adds its seconds live
    setVoiceListening(true);
    setAbraConnecting(true);
    const handle = await startDictation({
      // V1: bias the recogniser toward the names on THIS diagram. Computed at
      // OPEN because Deepgram fixes its keyword list when the socket opens —
      // which is also why the number-word elevation cannot live here and sits
      // in the pick handler instead.
      keyterms: diagramKeyterms(elementsRef.current.map((e) => e.label)),
      phone,
      onEngine: (e) => setAbraEngine(e),
      onReady: () => setAbraConnecting(false),
      // Show the command building: buffered fragments + the in-progress words.
      onInterim: (t) => { bumpAbraIdle(); setVoiceInterim((voiceBuffer.current ? voiceBuffer.current + " " : "") + t); },
      onText: (t) => {
        bumpAbraIdle();
        const txt = t.trim();
        if (!txt) return;
        // Spoken "stop" ALWAYS ends the session (stopWords.ts) — a numbered pick
        // ends with "done", so the two can no longer be confused.
        if (isMicStopWord(txt)) {
          voiceBuffer.current = "";
          stopAbraListening();
          return;
        }
        // A RELIABLE WAY OUT, WITHOUT STOPPING THE MICROPHONE.
        //
        // Paul, 2026-09-25: "I can't reliably exit the command after it
        // mis-hears. It keeps adding words like 'stop', 'done', 'cancel' and
        // 'exit'. The only way out is to stop and restart."
        //
        // Exactly so, and here is the mechanism. A mis-hear leaves a half
        // command in the buffer — "rename Task 8 to" — which `isIncompleteCommand`
        // then HOLDS, waiting up to three times 3.2s for the rest of the
        // sentence. Every word said during that hold is appended, including the
        // one meant to escape: "rename Task 8 to" + "cancel" becomes a complete
        // command that renames the element to "Cancel". The escape word was
        // being eaten by the thing it was trying to escape.
        //
        // `isMicStopWord` was already checked HERE, at the fragment, before the
        // buffer can swallow it — which is why "stop" worked and nothing else
        // did. A flow-end word now gets the same treatment: the buffer is
        // dropped unexamined, the pending flush is cancelled, and the word goes
        // on to close whatever is open.
        if (isFlowEndWord(txt)) {
          voiceBuffer.current = "";
          voiceWaits.current = 0;
          if (voiceFlushTimer.current) { clearTimeout(voiceFlushTimer.current); voiceFlushTimer.current = null; }
          setVoiceInterim("");
          const anythingOpen = !!(renameFlowRef.current || messageFlowRef.current || dividerFlowRef.current
            || templateFlowRef.current || pickFlowRef.current || pendingConfirmRef.current);
          if (anythingOpen) {
            // Let the runner close it properly — each flow has its own tidy-up.
            void runAbraCommandRef.current(txt);
          } else {
            // Nothing open: the half-command is already gone, which IS the
            // reset. Say so rather than sending a bare "cancel" to the AI,
            // which would cost a metered call to accomplish nothing.
            appendLog({ heard: txt, summary: "cleared — listening for the next command", ok: true });
          }
          return;
        }
        // Accumulate this fragment and restart the silence timer. A fresh
        // fragment may complete a held command, so re-evaluate from scratch.
        voiceBuffer.current = (voiceBuffer.current ? voiceBuffer.current + " " : "") + txt;
        voiceWaits.current = 0;
        setVoiceInterim(voiceBuffer.current);
        const buf = voiceBuffer.current.trim();
        // #5 Instant: show badges the moment a "rename <type>" is heard, and pick
        // a number the moment it's spoken — skip the silence wait entirely.
        const flow = renameFlowRef.current;
        // A number on its own is picked AT ONCE (the quick path) — the flow moves on to "say the new name". But a number
        // FOLLOWED BY WORDS has begun a name, and the rest may still be coming ("thirteen Approve" … a pause … "Order"):
        // running it now would rename the item "Approve" and then reject "Order" as an answer with no number. Those wait for
        // the normal quiet window like every other fragment (Paul, 2026-10-01: "you have to speak very quickly").
        if (flow?.phase === "pick") {
          const lead = leadingSpokenNumber(restoreLostOneNumber(buf));
          if (lead && !lead.rest) { flushVoiceBuffer(true); return; }
        }
        if (!flow) { const p = parseCommand(buf); if (p && p.length === 1 && p[0].op === "renameByType") { flushVoiceBuffer(true); return; } }
        if (voiceFlushTimer.current) clearTimeout(voiceFlushTimer.current);
        voiceFlushTimer.current = setTimeout(() => flushVoiceBuffer(), ABRA_SILENCE_MS);
      },
      onError: (msg) => appendLog({ heard: "", summary: msg, ok: false }),
      onEnd: () => { voiceDictRef.current = null; setVoiceListening(false); setAbraConnecting(false); flushVoiceBuffer(true); },
    });
    // A start that failed (or was stopped while connecting) never leaves "connecting…" up.
    if (!handle || voiceStopRequested.current) { handle?.stop(); voiceDictRef.current = null; setVoiceListening(false); setAbraConnecting(false); return; }
    voiceDictRef.current = handle;
    bumpAbraIdle(); // start the idle clock even if no voice ever arrives
  }, [voiceListening, stopAbraListening, flushVoiceBuffer, bumpAbraIdle, appendLog]);

  // Escape cancels a guided pick (rename or message) at any phase.
  useEffect(() => {
    if (!renameFlow && !messageFlow && !pickFlow && !templateFlow && !dividerFlow) return;
    const onKey = (e: KeyboardEvent) => {
      if (e.key !== "Escape") return;
      if (renameFlow) cancelRenameFlow("rename cancelled");
      if (messageFlow) { setMessageFlow(null); appendLog({ heard: "", summary: "message cancelled", ok: true }); }
      if (pickFlow) { setPickFlow(null); appendLog({ heard: "", summary: "cancelled", ok: true }); }
      if (dividerFlow) { setDividerFlow(null); appendLog({ heard: "", summary: "dividers closed", ok: true }); }
      // Esc takes the provisional template back off with it — the window is
      // shut either way, and leaving a half-chosen template behind would be
      // the one outcome nobody asked for.
      if (templateFlow) {
        const summary = closeTemplateFlowRef.current(false);
        appendLog({ heard: "", summary, ok: true });
      }
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [renameFlow, messageFlow, pickFlow, templateFlow, dividerFlow, cancelRenameFlow, setMessageFlow, setPickFlow, setDividerFlow, appendLog]);

  // Stop the mic when the mode is turned off or the editor unmounts.
  useEffect(() => {
    if (!voiceAssistOn && voiceDictRef.current) stopAbraListening();
  }, [voiceAssistOn, stopAbraListening]);
  useEffect(() => () => { voiceDictRef.current?.stop(); }, []);

  return {
    abraConnecting, abraEngine, annotateCommand, appendLog, armDebugBefore, armGoldFlash, clearVoiceLog, closeTemplateFlowRef, debugSaveState, debugSnapshots, downloadDebugSession, fetchAbraCost, goldFlash, onScreenBadges, onScreenRulers, pickTemplateCardRef, pointerWorld, reanchorTemplateRef, runVoiceCommand, saveDebugSession, setTemplateFlow, setVoiceAssistOn, setVoiceDebugRecording, stopAbraListening, takeDebugSnapshot, templateFlow, templateFlowRef, templatePickSeqRef, templateScrollRef, toggleAbraListening, voiceAssistOn, voiceBusy, voiceDebugRecording, voiceInterim, voiceLastId, voiceListening, voiceLog, renameFlow, messageFlow, pickFlow, dividerFlow, dividerMemRef, pendingConfirmRef, voiceQueueRef, voiceBusyRef,
  };
}
