import { NextResponse } from "next/server";
import { readFileSync } from "fs";
import { join } from "path";
import { SCHEMA_VERSION, PRODUCT_VERSION } from "@/app/lib/diagram/types";

export async function GET() {
  // The XSD carries the integer schema version (SCHEMA_VERSION) on version=, and the
  // Diagramatix PRODUCT version as appVersion in the annotation (clients that resolve
  // appVersion by fetching this route + regexing "Generated by Diagramatix X" get the
  // product version for free). The git build count is a display-only suffix on the
  // header badge, not part of the stamped product version.
  const appVersion = PRODUCT_VERSION;

  const xsdPath = join(process.cwd(), "public", "diagramatix-export.xsd");
  const xsdTemplate = readFileSync(xsdPath, "utf8");
  const xsd = xsdTemplate
    .replace("{{SCHEMA_VERSION}}", SCHEMA_VERSION)
    .replace("{{APP_VERSION}}", appVersion);

  return new NextResponse(xsd, {
    headers: {
      "Content-Type": "application/xml; charset=utf-8",
      "Content-Disposition": `inline; filename="diagramatix-export-schema-v${SCHEMA_VERSION}.xsd"`,
    },
  });
}
