/**
 * "What else is on this diagram?" — the small feature badges shown against a
 * diagram's name in the project navigation tree.
 *
 * A diagram is no longer just shapes. It may carry the AI prompt that generated
 * it, simulation parameters, an APQC classification, Risk & Control annotations,
 * a mined origin, an SOP. None of that is visible from the name, so a project of
 * sixty diagrams gives no clue which ones are wired up — you open them to find
 * out.
 *
 * Two rules this file exists to keep:
 *
 * 1. **Every badge is DERIVED from the same predicate the feature itself uses.**
 *    `hasSimData` is the one Clear-all uses; `hasRiskControl` is the one the RCM
 *    export uses. A badge with its own private idea of "has simulation data"
 *    would eventually contradict the panel that owns the data, and the badge is
 *    the one nobody would think to distrust.
 * 2. **Absent means absent, not false.** A badge appears only on positive
 *    evidence. Anything that cannot be determined from what the caller passed in
 *    is simply not claimed — see `mined`, which no amount of reading `data` can
 *    answer because the relationship lives in another table.
 */

import type { DiagramData } from "./types";
import { hasSimData } from "@/app/lib/simulation/clearSimData";
import { hasRiskControl } from "./riskControl";
import type { FeatureColorKey } from "@/app/lib/theme/featureColors";

/** The badges, in the order they read on the row. */
export type DiagramBadgeKey = "ai" | "simulator" | "mining" | "apqc" | "riskControl";

export interface DiagramBadge {
  key: DiagramBadgeKey;
  /** The two letters in the circle. */
  code: string;
  /** Hover text — says what is there, not just that something is. */
  title: string;
  /** Which Feature Colour it takes, so a badge matches its feature's tiles. */
  color: FeatureColorKey;
}

/** Facts that do not live in the diagram's own `data` and must be supplied. */
export interface BadgeContext {
  /**
   * This diagram is a mining run's discovered/reference model, or the object
   * model behind one. Resolved by the caller from ProcessMiningRun rows, since
   * the link is held there and a diagram cannot know it has been mined into.
   */
  mined?: boolean;
}

/**
 * The badges for one diagram. Pure, so the tree, a tooltip and a test all agree.
 *
 * `data` is typed loose because the project screen carries diagrams as Prisma
 * JSON; a malformed or absent value yields no badges rather than throwing, which
 * matters when one bad row would otherwise blank the whole tree.
 */
export function diagramFeatureBadges(data: unknown, ctx: BadgeContext = {}): DiagramBadge[] {
  const badges: DiagramBadge[] = [];
  const d = asDiagramData(data);

  if (d?.aiGeneration?.promptId) {
    badges.push({
      key: "ai", code: "AI", color: "ai",
      title: `Generated by AI from the prompt "${d.aiGeneration.promptName || "(unnamed)"}"`,
    });
  }

  if (d && hasSimData(d)) {
    badges.push({
      key: "simulator", code: "SI", color: "simulator",
      title: "Has simulation data — cycle times, arrival rates or branch percentages",
    });
  }

  if (ctx.mined) {
    badges.push({
      key: "mining", code: "MN", color: "mining",
      title: "Tied to a process-mining run in this project — discovered from, or compared against, an event log",
    });
  }

  const pcf = d?.pcf;
  if (pcf && typeof pcf === "object" && (pcf as { pcfId?: unknown }).pcfId !== undefined) {
    const p = pcf as { pcfId?: unknown; name?: unknown; hierarchyId?: unknown };
    const ref = [p.hierarchyId, p.name].filter(Boolean).join(" ");
    badges.push({
      key: "apqc", code: "AP", color: "apqc",
      title: ref ? `Classified in the APQC PCF: ${ref}` : "Classified in the APQC Process Classification Framework",
    });
  }

  const rcCount = d ? d.elements.filter((el) => hasRiskControl(el)).length : 0;
  if (rcCount > 0) {
    badges.push({
      key: "riskControl", code: "RC", color: "riskControl",
      title: `${rcCount} step${rcCount === 1 ? "" : "s"} carry Risk & Control annotations`,
    });
  }

  return badges;
}

/** Narrow unknown JSON to something with the shape the badges read. */
function asDiagramData(data: unknown): DiagramData | null {
  if (!data || typeof data !== "object") return null;
  const d = data as Partial<DiagramData>;
  if (!Array.isArray(d.elements) || !Array.isArray(d.connectors)) return null;
  return d as DiagramData;
}
