/**
 * Narrative BPMN prompts for the AI conformance harness
 * (scripts/ai-conformance-report.ts). A broad corpus (~40 prompts) chosen so that, between them,
 * the AI is asked to produce as much of the BPMN palette as possible — events,
 * gateways, task types, subprocesses, loops/multi-instance, data, pools/lanes
 * and advanced constructs — plus a few known router stressors (back-edges,
 * length, fan-in/out).
 *
 * IMPORTANT: the prompt text is deliberately NARRATIVE, not technical. A real
 * user describes a business process in plain prose ("if they haven't decided
 * within two days it's escalated"), not in BPMN jargon ("a timer boundary
 * event"). The harness tests whether the AI correctly INFERS the right notation
 * from natural language — so do not name BPMN constructs in the prompts. The
 * `name` field is just an internal label (used to name the saved diagram).
 *
 * Keep this set STABLE so conformance trends are comparable across runs; add new
 * prompts rather than rewording existing ones. This doubles as the golden corpus
 * for any future router rewrite (run old vs new over the same corpus and compare).
 */
export interface BpmnPrompt {
  name: string;
  prompt: string;
}

export const BPMN_PROMPTS: BpmnPrompt[] = [
  // --- Core flow ---
  { name: "linear-order", prompt: "A customer places an order, the system validates it, the warehouse ships the goods, and the order is complete." },
  { name: "approval-decision", prompt: "An employee submits a leave request. The manager reviews it and either approves or rejects it. Either way the employee is told the outcome, and the request is closed." },
  { name: "parallel-onboarding", prompt: "When a new hire accepts an offer, the company sets up their IT accounts, prepares their desk, and enrols them in payroll — all at the same time. Once those are all done, they attend a welcome meeting." },
  { name: "service-request", prompt: "A user logs an IT support ticket. The service desk works out what's wrong, fixes it, and closes the ticket once the user confirms it's sorted." },

  // --- Start / end variety ---
  { name: "scheduled-billing", prompt: "At the end of every month the company automatically prepares each customer's invoice and emails it to them." },
  { name: "incoming-order", prompt: "Whenever a purchase order arrives from a customer, the company registers it, fulfils it, and completes the order." },
  { name: "product-recall", prompt: "When a product recall is declared, every regional team is alerted at once. Each region confirms it has acted, and then the recall is closed." },
  { name: "payment-failure", prompt: "The system charges the customer's card. If it goes through, the order is confirmed. If the card is declined, the order can't go ahead and the finance team is alerted to follow up." },
  { name: "emergency-stop", prompt: "If a serious fault is detected while the line is running, the operator is alerted and everything stops immediately — nothing else continues." },

  // --- Waiting / time / external replies ---
  { name: "free-trial", prompt: "A customer starts a free trial. Two weeks later the company checks whether they've upgraded: if they have, the account becomes a paid one; if not, the trial expires." },
  { name: "await-credit-report", prompt: "After someone submits an application, the company has to wait for the credit bureau to send back its report before it can make a decision." },
  { name: "notify-shipment", prompt: "The warehouse picks the goods, lets the customer know their shipment is on its way, and the carrier then collects it." },
  { name: "reorder-on-low-stock", prompt: "The system keeps an eye on inventory. Whenever stock drops below the reorder level it raises a replenishment order, and then carries on watching." },

  // --- Things that can interrupt / time out ---
  { name: "review-deadline", prompt: "A manager reviews a request. If they haven't decided within two days it's automatically escalated to the director; otherwise their decision stands and the request continues." },
  { name: "import-retry-on-error", prompt: "The system imports a data file. If the file turns out to be invalid, someone corrects it and the import is tried again; once it's clean, the records are loaded." },
  { name: "cancel-while-assessing", prompt: "An assessor works through a case. If a cancellation comes in from the customer while they're still working on it, the case is dropped and a refund is issued instead." },
  { name: "progress-updates", prompt: "While a long job is being processed, a status update goes out every hour to keep everyone informed, and the job keeps running until it's finished." },

  // --- Branching / decisions ---
  { name: "risk-routing", prompt: "A loan application is assessed for risk. High-risk applications go to manual underwriting, medium-risk ones get a standard review, and low-risk ones are approved automatically. Whichever path it takes, the decision is then issued." },
  { name: "concurrent-checks", prompt: "After a passport application is submitted, a background check, document verification, and a photo capture all happen together. Only once all three are finished is the passport printed." },
  { name: "optional-assessments", prompt: "Depending on the insurance claim, it may need any combination of a medical review, a vehicle inspection, and a police-report check. Whichever ones apply are carried out, and once they're all back the claim is settled." },
  { name: "payment-or-timeout", prompt: "After the invoice is sent, the company waits to see which happens first: if the payment arrives, a receipt is issued; if thirty days pass with no payment, a reminder is sent out." },
  { name: "two-of-three-vote", prompt: "Three reviewers consider a proposal at the same time. As soon as any two of them have approved it, the proposal is ratified." },

  // --- Who does what (task variety) ---
  { name: "expense-claim", prompt: "An employee fills in an expense claim. The system automatically checks the receipts, a manager approves it, and the system then schedules the reimbursement." },
  { name: "goods-receipt", prompt: "A dock worker unloads the delivery truck by hand, then scans the items into the system, and the stock levels update automatically." },
  { name: "apply-discount", prompt: "An order is captured, the right discount is worked out from the pricing policy, and the final price is applied and confirmed." },
  { name: "supplier-exchange", prompt: "The company issues a purchase order to the supplier, waits for the supplier's confirmation to come back, and then schedules the goods to be received." },

  // --- Grouped / reusable / nested work ---
  { name: "fulfilment-detail", prompt: "An order comes in. Fulfilling it means picking, packing, and shipping the goods. After fulfilment is done, the customer is invoiced." },
  { name: "interview-round", prompt: "Candidates are screened, then a round of interviews is conducted, and finally an offer is made to the chosen candidate." },
  { name: "cancel-anytime", prompt: "An order is paid for and then shipped. At any time before it ships, if the customer cancels, the order is stopped and their money is refunded." },
  { name: "reuse-credit-check", prompt: "A loan application comes in. The company runs its usual credit check on the applicant, and based on the result the loan is approved or declined." },
  { name: "book-trip-allornothing", prompt: "A trip is booked by reserving a flight and a hotel together. If either reservation can't be made, the other is cancelled and the whole booking is undone so nothing is left half-booked." },

  // --- Information being used ---
  { name: "contract-lifecycle", prompt: "A contract is drafted, the legal team reviews the draft, and once everyone's happy it's signed and filed away." },
  { name: "customer-lookup", prompt: "A verification request comes in. The customer's details are looked up in the customer records, the record is brought up to date, and the request is confirmed." },
  { name: "monthly-report", prompt: "Starting from the month's raw figures, the team puts together a monthly report and sends it out to stakeholders." },

  // --- Multiple parties / hand-offs ---
  { name: "three-team-claim", prompt: "A claim passes through three teams: customer service logs it, an assessor evaluates it, and finance pays it out. Show how it's handed from one team to the next." },
  { name: "customer-supplier", prompt: "A customer and a supplier deal with each other: the customer sends a purchase order, the supplier confirms it, ships the goods, and sends an invoice; the customer receives the goods and pays. Show the back-and-forth between the two organisations." },
  { name: "external-payment", prompt: "A booking company takes payment through an outside payment provider: it sends the charge to the provider and gets a result back. The provider's own internal steps aren't shown — only the exchange with it." },

  // --- Loops / repetition / scale ---
  { name: "rework-loop", prompt: "An author drafts a document, then a reviewer reviews it. If changes are requested, the author revises it and it goes back for another review, and this repeats until the reviewer is happy. Once approved, the document is published." },
  { name: "inspect-batch", prompt: "An inspector checks each item in a batch, one after another, repeating until every item in the batch has been inspected, after which the batch is released." },
  { name: "collect-approvals", prompt: "A purchase requisition needs sign-off from several approvers. Each approver reviews it, and once they have all responded the requisition is finalised." },
  { name: "long-claim-flow", prompt: "An insurance claim works through a long sequence of steps: it's received, registered, the policy is validated, coverage is checked, an assessor is assigned, an inspection is scheduled and then carried out, the damage is estimated, the estimate is reviewed, the outcome is decided, the payout is calculated, approval is obtained, payment is issued, the customer is notified, and finally the claim is closed." },
  { name: "five-way-approval", prompt: "After a purchase requisition is submitted it goes to five approvers at once — finance, procurement, legal, security, and the department head. Only once all five have approved is the purchase order raised." },

  // === Complex set: nested sub-processes (EPs within EPs), gateways inside
  // sub-processes, rework/redo loops, edge-mounted (boundary) events, and
  // multiple lanes with sub-lanes. Still narrative — the complexity should make
  // the AI reach for nesting, sub-lanes, boundary events and loops on its own. ===
  { name: "mortgage-origination", prompt: "A bank handles a mortgage application across its Front Office and Risk department, and within Risk there are separate Underwriting and Valuation teams. After the application is captured, it goes into an underwriting stage that breaks down into its own steps: pull the credit file, assess affordability, and order a property valuation — and that valuation is itself a smaller process of booking a surveyor, inspecting the property, and producing a report. Inside underwriting, if the risk score is high the file is sent for manual review, if it's borderline extra documents are requested and the applicant has to resubmit (which loops back to the affordability assessment), and if it's low it's auto-approved. If the applicant doesn't return requested documents within ten days, the application lapses. Once underwriting concludes, the Front Office either issues the offer or declines." },
  { name: "claims-adjudication", prompt: "An insurer adjudicates a claim through its Customer Service, Assessment, and Payments teams, with Assessment further split into Desk Assessors and Field Assessors. The claim is registered, then enters an assessment stage made up of validating cover, estimating the loss, and running a fraud check; the fraud check is its own little process of scoring indicators, and if anything looks suspicious it spins off a separate investigation. Within assessment, depending on the value the claim is either fast-tracked, sent to a desk assessor, or assigned to a field assessor who must physically inspect. If the estimate is disputed it goes back to be re-estimated, repeating until it's agreed. While a field assessment is underway, a customer cancellation stops it and moves to a refund. Finally Payments settles or the claim is denied." },
  { name: "software-release-pipeline", prompt: "An engineering org ships a release through Development, QA, and Operations lanes, and QA is split into Automated Testing and Manual Testing sub-teams. The pipeline runs a build stage, then a test stage that contains unit tests, integration tests, and a security scan; if any test fails the work goes back to development for a fix and the whole test stage runs again, looping until everything passes. After tests, a deployment stage stages the release, runs smoke checks, and promotes to production — but if the smoke checks fail it automatically rolls back. If a release is still not promoted after its scheduled window, it's deferred to the next train." },
  { name: "customer-onboarding-kyc", prompt: "A fintech onboards a customer across its Onboarding and Compliance departments, and Compliance has Junior Analysts and Senior Analysts as sub-teams. After sign-up, identity verification runs as its own stage of document capture, biometric check, and a sanctions screen; the sanctions screen, if it raises a hit, branches into an enhanced due-diligence sub-process. Depending on the risk rating the case is auto-cleared, sent to a junior analyst, or escalated to a senior analyst, and if the senior analyst needs more information the customer is asked to provide it and the verification stage repeats. If the customer doesn't complete verification within seven days the application expires, and only a cleared customer gets their account activated." },
  { name: "procurement-rfp", prompt: "A company runs a competitive tender through its Procurement and Evaluation teams, with Evaluation split into Technical and Commercial panels. After requirements are agreed, the tender goes out and bids come back, then an evaluation stage scores each bid — technical scoring and commercial scoring happen in parallel inside it, and a shortlisting decision either proceeds to negotiation or, if no bid is acceptable, sends the requirement back to be re-scoped and re-issued (a loop). Negotiation is its own stage of clarifications, best-and-final offers, and a final decision; if the preferred supplier fails due diligence the panel falls back to the runner-up. Award is then approved or the tender is cancelled." },
  { name: "manufacturing-work-order", prompt: "A factory fulfils a work order across Planning, Production, and Quality lanes, and Production is divided into the Machining and Assembly cells. The order is scheduled, then a production stage runs machining followed by assembly, with each cell doing its own setup, run, and in-line check. After production, a quality gate inspects the batch: if it passes it's released, if it has minor defects it goes back for rework and is re-inspected (looping until acceptable), and if it has major defects it's scrapped and the order is re-planned. If a machine breakdown interrupts the machining step, the order is rescheduled." },
  { name: "incident-management", prompt: "An IT service desk manages incidents across Tier 1, Tier 2, and Tier 3 support lanes, with Tier 2 split into Network and Application specialists. A ticket is logged and triaged, then a diagnosis stage tries to reproduce, isolate, and identify the root cause; if Tier 1 can't resolve it, it's escalated to the relevant Tier 2 specialist, and if they can't either it goes to Tier 3. A fix is applied and verified with the user — if the user says it's still broken the incident is reopened and diagnosis starts again. If a Priority 1 incident isn't resolved within its target time, it's automatically escalated to the duty manager. Finally the incident is closed." },
  { name: "grant-review", prompt: "A foundation reviews grant applications through its Programs and Review Committee groups, and the committee has Primary Reviewers and a Chair as sub-roles. An application is screened for eligibility, then enters a review stage where three reviewers independently score it and the scores are reconciled; if reviewers disagree beyond a threshold the application is sent back for an additional review (a loop). Depending on the reconciled score it's recommended for funding, waitlisted, or declined, and waitlisted applications loop back into the next funding round. If the applicant is asked to revise the budget and doesn't within the deadline, the application is withdrawn. Approved grants move to award." },
  { name: "visa-processing", prompt: "An immigration office processes a visa across Intake, Adjudication, and Security lanes, with Security split into Document Forensics and Background Checks. After lodgement, an adjudication stage checks completeness, verifies documents, and runs a security clearance; the clearance is its own process of an identity check and a watchlist screen, and a hit there branches into a manual security review. Inside adjudication, if information is missing the applicant is asked for more and the case repeats once the response arrives; if the response doesn't come within the deadline the case is refused. Depending on the outcome the visa is granted, refused, or referred to a senior officer." },
  { name: "patient-pathway", prompt: "A hospital runs an emergency patient pathway across Triage, Treatment, and Discharge teams, and Treatment is divided into Nursing and Physician sub-lanes. The patient is triaged, then a treatment stage assesses, investigates, and treats; investigation is its own sub-process of ordering tests, collecting samples, and reviewing results, and if a result is abnormal the test is repeated. Depending on severity the patient is fast-tracked, admitted, or referred to a specialist, and an admitted patient whose condition deteriorates is escalated to intensive care. Once stable, a discharge stage arranges medication, follow-up, and transport, then the patient is discharged." },
  { name: "supply-replenishment", prompt: "A retailer replenishes stock across Planning, Procurement, and Logistics lanes, with Procurement split into Domestic and Import buyers. Demand is forecast, then a replenishment stage decides quantities, raises orders, and confirms with suppliers; ordering is its own process of selecting a supplier, checking the contract, and issuing the order. If a supplier can't confirm, the buyer falls back to an alternate supplier and re-issues (a loop). Imported orders branch into a customs sub-process. If goods don't arrive by the promised date, an expedite path is triggered. Received goods are put away or, if damaged, returned." },
  { name: "fraud-investigation", prompt: "A bank investigates suspected fraud across Monitoring, Investigation, and Recovery teams, and Investigation has Analysts and a Case Manager. An alert is triaged, then an investigation stage gathers transactions, interviews the customer, and assesses evidence; evidence assessment is its own sub-process of scoring indicators and, if needed, requesting records from third parties — and a slow third party that doesn't respond in time triggers a chase. Depending on findings the case is closed as a false alarm, confirmed as fraud, or sent back for more evidence (a loop). Confirmed cases go to recovery, and a customer dispute reopens the case." },
  { name: "construction-permit", prompt: "A council approves a building permit across Intake, Planning, and Building Control departments, with Planning split into Zoning and Heritage officers. The application is lodged and checked for completeness, then a review stage runs a planning assessment and a building-code assessment in parallel; the planning assessment itself branches by zone into a standard or a heritage review. If either assessment finds problems the applicant must revise and resubmit, and the review repeats until both are satisfied. If the applicant doesn't respond to a request for information within the statutory period, the application is deemed withdrawn. Finally the permit is granted or refused." },
  { name: "credit-card-dispute", prompt: "A card issuer handles a dispute across Customer Service, Disputes, and Settlement teams, and Disputes is split into First-Line and Specialist handlers. The dispute is logged and provisional credit is decided, then an investigation stage gathers the transaction, contacts the merchant, and assesses the claim; if the merchant contests it, a representment sub-process runs and the case may bounce back for re-assessment (a loop). Depending on the outcome the dispute is upheld, the merchant is charged back, or it's declined and the provisional credit reversed. If the merchant doesn't respond within the network deadline, the chargeback proceeds automatically." },
  { name: "lab-testing", prompt: "A clinical lab processes a specimen across Accessioning, Analysis, and Reporting lanes, with Analysis divided into Chemistry and Microbiology benches. The specimen is accessioned, then an analysis stage prepares the sample, runs the assay, and validates the result; validation is its own process of a QC check and a plausibility check, and an out-of-range result triggers a re-test that loops back to running the assay. Depending on the analyte the sample is routed to chemistry or microbiology, and a critical result is flagged for immediate clinician notification. If the sample degrades before analysis, a recollection is requested. Validated results are reported." },
  { name: "recruitment-end-to-end", prompt: "A company recruits across HR and Hiring-Manager lanes, with HR split into Sourcing and Coordination sub-teams. Applications are screened, then an interview stage runs a phone screen, a technical round, and a panel; each round has a pass/fail decision and a failed candidate exits, while a strong candidate proceeds. Offer is its own sub-process of approval, drafting, and negotiation — and if the candidate counters, it loops back through approval. If a candidate doesn't respond to an interview invite within five days they're marked inactive. An accepted offer moves to onboarding; a declined one reopens sourcing." },
  { name: "prior-authorization", prompt: "A health plan handles a prior-authorization request across Intake, Clinical Review, and Appeals lanes, and Clinical Review has Nurse Reviewers and Medical Directors. The request is received and checked for completeness, then a clinical review stage applies criteria, gathers records, and makes a determination; if the nurse can't approve under the criteria it's escalated to a medical director. A denial opens an appeals sub-process of reconsideration and, if needed, an independent review, and a successful appeal loops back to authorization. If the provider doesn't submit requested clinical notes within the deadline, the request is administratively denied." },
  { name: "customs-clearance", prompt: "A freight forwarder clears a shipment across Documentation, Customs, and Delivery teams, with Customs split into Classification and Inspection officers. Documents are prepared, then a clearance stage classifies the goods, calculates duty, and lodges the declaration; if customs selects the shipment for inspection, an inspection sub-process runs and either releases the goods or, on a discrepancy, holds them for amendment which loops back to the declaration. Duty must be paid before release, and if payment isn't made within the free-time window demurrage charges are triggered. Cleared goods move to delivery." },
  { name: "change-management", prompt: "An IT org runs change management across Requesters, the Change Team, and Operations, with the Change Team split into Coordinators and the Change Advisory Board. A change is raised and assessed for risk, then an approval stage routes it: low-risk changes are pre-approved, medium-risk go to a coordinator, and high-risk go to the full board. Implementation is its own sub-process of preparing, executing, and verifying — and if verification fails it triggers a rollback. A change that isn't completed inside its window is automatically rescheduled, and a rejected change loops back to the requester for rework." },
  { name: "warranty-claim", prompt: "A manufacturer handles a warranty claim across Service, Repair, and Finance lanes, and Repair is divided into Diagnostics and Bench technicians. The claim is logged and validated against entitlement, then a repair stage runs diagnosis, decides repair-or-replace, and carries out the work; diagnosis is its own process of testing, identifying the fault, and estimating, and an inconclusive diagnosis loops back for re-testing. If parts are unavailable the job waits, and if they don't arrive in time the claim is escalated. A repaired unit is re-inspected — failing re-inspection sends it back to the bench — and finance then approves any goodwill payment." },
  { name: "contract-lifecycle-negotiation", prompt: "A legal team manages a contract across Business, Legal, and Approvals lanes, with Legal split into Drafting and Review sub-roles. A request initiates a drafting stage of templating, clause selection, and an internal review; the review branches by value into a standard or an enhanced approval path. Negotiation is its own sub-process of exchanging redlines with the counterparty and reconciling positions, and each redline round loops back through internal review until both sides agree. If the counterparty goes silent past the deadline, the deal is paused. An approved contract is signed and filed; a rejected one returns to drafting." },
  { name: "academic-admissions", prompt: "A university admits students across Admissions and Faculty lanes, with Faculty split into a Review Committee and a Chair. Applications are screened for minimum requirements, then an evaluation stage assesses academics, references, and a portfolio; the portfolio assessment is its own sub-process and a borderline score triggers a second reader. Depending on the combined result the applicant is offered a place, waitlisted, or rejected, and waitlisted applicants loop into a later round as places free up. If an offered applicant doesn't accept within the deadline, the place is released to the waitlist." },
  { name: "account-opening-aml", prompt: "A bank opens a business account across Onboarding, Compliance, and Operations lanes, and Compliance is split into KYC Analysts and an MLRO. After application, a due-diligence stage verifies the entity, identifies beneficial owners, and screens them; beneficial-owner identification is its own nested process that can recurse through ownership layers, and a screening hit branches into enhanced due diligence. Depending on risk the account is approved, sent to an analyst, or escalated to the MLRO, and a request for missing ownership documents loops the stage until satisfied. If documents aren't supplied within the SLA, the application is declined." },
  { name: "discharge-planning", prompt: "A hospital coordinates discharge across the Ward, Pharmacy, and Social Care teams, with the Ward split into Nursing and Medical sub-lanes. Once a patient is deemed fit, a planning stage arranges medication, equipment, and follow-up in parallel; the medication step is its own sub-process of reconciliation, prescribing, and dispensing, and a flagged interaction loops back to reconciliation. Depending on needs the patient is discharged home, to rehab, or to social care, and a patient whose condition changes is re-assessed (looping back). If transport isn't confirmed by the planned time, discharge is deferred to the next day." },
  { name: "supplier-quality-audit", prompt: "A company audits a supplier across Quality, Supplier, and Management lanes, with Quality split into Auditors and a Lead Auditor. An audit is planned, then an execution stage reviews documents, inspects the site, and interviews staff; each finding is classified, and major findings open a remediation sub-process where the supplier submits a corrective action that is verified — failing verification loops back for another corrective action. If the supplier doesn't respond to findings within the agreed period, the audit is escalated to management. A passing audit certifies the supplier; a failing one suspends them." },
  { name: "service-provisioning", prompt: "A telco provisions a new service across Sales, Provisioning, and Field lanes, with Provisioning split into Network and Billing sub-teams. The order is validated, then a provisioning stage configures the network, sets up billing, and schedules an install; network configuration is its own process of allocating resources, applying config, and testing, and a failed test loops back to re-apply the config. If a site survey finds the address isn't serviceable, the order branches to an alternative-technology path. A field install that the customer isn't present for is rescheduled, and only a tested, active service is handed to billing to go live." },
  { name: "disaster-recovery-failover", prompt: "An operations team runs a disaster-recovery failover across the NOC, Infrastructure, and Application lanes, with Infrastructure split into Network and Storage sub-teams. On a declared outage, a failover stage validates the standby, redirects traffic, and verifies services; verification is its own sub-process of health checks and data-integrity checks, and a failed check triggers a rollback to the primary. Depending on the failure type either a partial or a full failover runs. If services aren't healthy within the recovery-time objective, the incident is escalated to a crisis bridge, and a flapping service loops through verification until stable." },
  { name: "billing-claims", prompt: "A medical practice bills payers across Coding, Billing, and Collections lanes, with Billing split into Submission and Follow-up sub-teams. An encounter is coded, then a submission stage scrubs the claim, checks eligibility, and submits; scrubbing is its own process of validating codes and catching edits, and a failed edit loops back for correction. A denied claim opens an appeals sub-process of review, rebuttal, and resubmission, looping until paid or written off. If a payer doesn't respond within the timely-filing window, the claim is escalated. Paid claims are reconciled; patient balances move to collections." },
  { name: "event-planning", prompt: "An agency plans a corporate event across Account, Production, and Logistics lanes, with Production split into Creative and Technical sub-teams. After the brief, planning runs three parallel sub-processes — secure the venue, arrange catering, and book production — each with its own steps and a go/no-go gate. The venue sub-process branches by size into a standard or a premium path, and if a vendor falls through the affected sub-process loops back to re-source. A combined readiness review either greenlights the event or sends weak areas back for rework. If final headcount isn't confirmed by the cut-off, catering defaults to the guaranteed minimum." },
  { name: "tenant-screening", prompt: "A letting agency screens a tenant across Lettings and Referencing lanes, with Referencing split into Credit and Affordability checkers. An application is taken, then a referencing stage runs identity, credit, affordability, and a landlord reference; the affordability check is its own sub-process and a borderline result triggers a guarantor path. Depending on the combined outcome the applicant is approved, conditionally approved, or declined, and a request for additional payslips loops the stage. If references aren't returned within five working days, the application is put on hold and the property re-listed." },
  { name: "loan-collections", prompt: "A lender manages arrears across Early Collections, Late Collections, and Recovery lanes, with Late Collections split into Negotiators and a Supervisor. An account enters a collections stage of contact attempts, an affordability assessment, and an arrangement; the assessment branches into a hardship sub-process when the borrower is struggling. A broken arrangement loops the account back to contact, and after a number of failed cycles it escalates to the next lane. If the borrower doesn't respond within the regulatory timeframe, a formal notice is issued, and unresolved accounts pass to recovery." },
  { name: "product-returns-rma", prompt: "A retailer handles returns across Customer Service, Warehouse, and Finance lanes, with the Warehouse split into Inspection and Restocking sub-teams. A return is authorised, then on arrival an inspection stage verifies the item, grades its condition, and decides disposition; grading is its own sub-process, and a disputed grade triggers a second inspection (a loop). Depending on disposition the item is restocked, refurbished, or scrapped, and a refund or replacement is issued accordingly. If the customer doesn't ship the item back within the RMA window, the authorisation expires." },
  { name: "clinical-trial-intake", prompt: "A research site enrols a participant across Recruitment, Clinical, and Regulatory lanes, with Clinical split into Coordinators and Investigators. A candidate is pre-screened, then an eligibility stage runs consent, screening tests, and an investigator review; the screening tests are their own sub-process and an out-of-range result triggers a confirmatory re-test. Depending on eligibility the candidate is enrolled, screen-failed, or referred for a waiver decision. If consent isn't completed within the screening window, the candidate is withdrawn, and a protocol deviation loops back to investigator review." },
  { name: "payroll-run", prompt: "A payroll team runs a monthly cycle across Data, Processing, and Approvals lanes, with Processing split into Calculation and Verification sub-teams. Inputs are collected, then a processing stage imports time, calculates gross-to-net, and verifies; verification is its own sub-process of variance checks and exception handling, and any exception loops back to recalculation. Depending on the variance the run is auto-approved, sent to a reviewer, or held for investigation. If approvals aren't completed by the bank cut-off, an emergency sub-run is triggered for affected employees, and the rest proceeds to payment." },
  { name: "rfp-vendor-evaluation", prompt: "A buyer evaluates vendors across Procurement and Stakeholder lanes, with Stakeholders split into Technical, Security, and Finance reviewers. After shortlisting, an evaluation stage runs technical, security, and financial assessments in parallel; the security assessment branches into a deeper audit for vendors handling sensitive data. Findings are consolidated and, if a vendor has gaps, they're asked to remediate and are re-assessed (a loop). Depending on the consolidated score a vendor is selected, held, or rejected. If a vendor misses the clarification deadline, they're eliminated, and the winner proceeds to contracting." },
  { name: "field-service-dispatch", prompt: "A utility dispatches field work across Dispatch, Field, and Back-Office lanes, with Field split into Junior and Senior technicians. A job is created and assessed, then a dispatch stage schedules, routes, and assigns; assignment branches by complexity to a junior or senior technician. On site, the work sub-process diagnoses, repairs, and tests — a failed test loops back to repair, and a job that needs a part not on the van is suspended and rescheduled. If the customer isn't present at the appointment, a no-access path triggers a re-book. Completed jobs are closed and invoiced." },
  { name: "underwriting-commercial", prompt: "A commercial insurer underwrites a policy across Broking, Underwriting, and Actuarial lanes, with Underwriting split into Underwriters and a Senior Referral desk. A submission is triaged, then an underwriting stage assesses the risk, prices it, and sets terms; risk assessment is its own sub-process of surveying the risk and modelling losses, and a large exposure is referred to the senior desk. If information is missing the broker is asked and the stage repeats once it's supplied. Depending on appetite the risk is quoted, declined, or referred to reinsurance. A quote not accepted within its validity period lapses." },
  { name: "onboarding-saas-enterprise", prompt: "A SaaS vendor onboards an enterprise customer across Customer Success, Implementation, and Support lanes, with Implementation split into Configuration and Integration sub-teams. After kickoff, an implementation stage runs configuration, data migration, and integration in sequence; data migration is its own sub-process of extract, transform, and load, and a validation failure loops back to transform. Integration branches by system landscape into a standard or a custom path. A user-acceptance gate either signs off or sends defects back for rework. If the customer doesn't sign off within the agreed window, the go-live is rescheduled and Support is briefed." },
  { name: "litigation-discovery", prompt: "A law firm runs a litigation matter across Partners, Associates, and Paralegals lanes, with Associates split into Litigation and Research sub-teams. After intake, a discovery stage collects documents, reviews them, and prepares production; document review is its own sub-process of a first-pass review, a privilege check, and a quality check, and any document marked uncertain loops back for a second review. Depending on findings the matter proceeds to settlement talks or to trial preparation, and if opposing counsel raises a deficiency the production is revised and reissued. If a court-imposed deadline is about to pass, the team files for an extension, and a settlement reached at any point ends the matter early." },
  { name: "loan-restructure", prompt: "A bank restructures a distressed loan across Relationship, Credit, and Approvals lanes, with Credit split into Analysts and a Credit Committee. After a hardship request, an assessment stage reviews the borrower's position, models repayment options, and recommends a structure; the modelling is its own sub-process of stress-testing each option, and an option that fails the stress test is discarded and the modelling repeats. Depending on the exposure the recommendation is approved by an analyst, the committee, or escalated to the board, and a rejected proposal loops back for re-modelling. If the borrower doesn't return signed terms within the offer period, the original terms stand and the account moves to monitoring." },
];
