/**
 * Narrative BPMN prompts for the AI conformance harness
 * (scripts/ai-conformance-report.ts). A curated set of 20 prompts: ~4 simple
 * baselines plus the complex narratives that reliably stress nested
 * sub-processes (EPs within EPs), gateways inside them, rework/redo loops,
 * boundary events and multi-lane/sub-lane structures — i.e. the ones that
 * surface the router/layout defects (Cause A coincidence, Cause B dense-column
 * crossings). Trimmed from 82 on 2026-06-30; the dropped prompts were redundant
 * simple narratives. Deterministic repro of the defects lives in
 * tests/conformance/fixtures + known-defects.test.ts, immune to generation
 * non-determinism.
 *
 * IMPORTANT: the prompt text is deliberately NARRATIVE, not technical. A real
 * user describes a business process in plain prose ("if they haven't decided
 * within two days it's escalated"), not in BPMN jargon ("a timer boundary
 * event"). The harness tests whether the AI correctly INFERS the right notation
 * from natural language — so do not name BPMN constructs in the prompts. The
 * `name` field is just an internal label (used to name the saved diagram).
 *
 * Keep this set STABLE so conformance trends are comparable across runs; add new
 * prompts rather than rewording existing ones. This doubles as the golden corpus
 * for any future router rewrite (run old vs new over the same corpus and compare).
 */
export interface BpmnPrompt {
  name: string;
  prompt: string;
}

export const BPMN_PROMPTS: BpmnPrompt[] = [
  { name: "linear-order", prompt: "A customer places an order, the system validates it, the warehouse ships the goods, and the order is complete." },
  { name: "approval-decision", prompt: "An employee submits a leave request. The manager reviews it and either approves or rejects it. Either way the employee is told the outcome, and the request is closed." },
  { name: "customer-supplier", prompt: "A customer and a supplier deal with each other: the customer sends a purchase order, the supplier confirms it, ships the goods, and sends an invoice; the customer receives the goods and pays. Show the back-and-forth between the two organisations." },
  { name: "rework-loop", prompt: "An author drafts a document, then a reviewer reviews it. If changes are requested, the author revises it and it goes back for another review, and this repeats until the reviewer is happy. Once approved, the document is published." },
  { name: "mortgage-origination", prompt: "A bank handles a mortgage application across its Front Office and Risk department, and within Risk there are separate Underwriting and Valuation teams. After the application is captured, it goes into an underwriting stage that breaks down into its own steps: pull the credit file, assess affordability, and order a property valuation — and that valuation is itself a smaller process of booking a surveyor, inspecting the property, and producing a report. Inside underwriting, if the risk score is high the file is sent for manual review, if it's borderline extra documents are requested and the applicant has to resubmit (which loops back to the affordability assessment), and if it's low it's auto-approved. If the applicant doesn't return requested documents within ten days, the application lapses. Once underwriting concludes, the Front Office either issues the offer or declines." },
  { name: "claims-adjudication", prompt: "An insurer adjudicates a claim through its Customer Service, Assessment, and Payments teams, with Assessment further split into Desk Assessors and Field Assessors. The claim is registered, then enters an assessment stage made up of validating cover, estimating the loss, and running a fraud check; the fraud check is its own little process of scoring indicators, and if anything looks suspicious it spins off a separate investigation. Within assessment, depending on the value the claim is either fast-tracked, sent to a desk assessor, or assigned to a field assessor who must physically inspect. If the estimate is disputed it goes back to be re-estimated, repeating until it's agreed. While a field assessment is underway, a customer cancellation stops it and moves to a refund. Finally Payments settles or the claim is denied." },
  { name: "manufacturing-work-order", prompt: "A factory fulfils a work order across Planning, Production, and Quality lanes, and Production is divided into the Machining and Assembly cells. The order is scheduled, then a production stage runs machining followed by assembly, with each cell doing its own setup, run, and in-line check. After production, a quality gate inspects the batch: if it passes it's released, if it has minor defects it goes back for rework and is re-inspected (looping until acceptable), and if it has major defects it's scrapped and the order is re-planned. If a machine breakdown interrupts the machining step, the order is rescheduled." },
  { name: "visa-processing", prompt: "An immigration office processes a visa across Intake, Adjudication, and Security lanes, with Security split into Document Forensics and Background Checks. After lodgement, an adjudication stage checks completeness, verifies documents, and runs a security clearance; the clearance is its own process of an identity check and a watchlist screen, and a hit there branches into a manual security review. Inside adjudication, if information is missing the applicant is asked for more and the case repeats once the response arrives; if the response doesn't come within the deadline the case is refused. Depending on the outcome the visa is granted, refused, or referred to a senior officer." },
  { name: "credit-card-dispute", prompt: "A card issuer handles a dispute across Customer Service, Disputes, and Settlement teams, and Disputes is split into First-Line and Specialist handlers. The dispute is logged and provisional credit is decided, then an investigation stage gathers the transaction, contacts the merchant, and assesses the claim; if the merchant contests it, a representment sub-process runs and the case may bounce back for re-assessment (a loop). Depending on the outcome the dispute is upheld, the merchant is charged back, or it's declined and the provisional credit reversed. If the merchant doesn't respond within the network deadline, the chargeback proceeds automatically." },
  { name: "warranty-claim", prompt: "A manufacturer handles a warranty claim across Service, Repair, and Finance lanes, and Repair is divided into Diagnostics and Bench technicians. The claim is logged and validated against entitlement, then a repair stage runs diagnosis, decides repair-or-replace, and carries out the work; diagnosis is its own process of testing, identifying the fault, and estimating, and an inconclusive diagnosis loops back for re-testing. If parts are unavailable the job waits, and if they don't arrive in time the claim is escalated. A repaired unit is re-inspected — failing re-inspection sends it back to the bench — and finance then approves any goodwill payment." },
  { name: "discharge-planning", prompt: "A hospital coordinates discharge across the Ward, Pharmacy, and Social Care teams, with the Ward split into Nursing and Medical sub-lanes. Once a patient is deemed fit, a planning stage arranges medication, equipment, and follow-up in parallel; the medication step is its own sub-process of reconciliation, prescribing, and dispensing, and a flagged interaction loops back to reconciliation. Depending on needs the patient is discharged home, to rehab, or to social care, and a patient whose condition changes is re-assessed (looping back). If transport isn't confirmed by the planned time, discharge is deferred to the next day." },
  { name: "service-provisioning", prompt: "A telco provisions a new service across Sales, Provisioning, and Field lanes, with Provisioning split into Network and Billing sub-teams. The order is validated, then a provisioning stage configures the network, sets up billing, and schedules an install; network configuration is its own process of allocating resources, applying config, and testing, and a failed test loops back to re-apply the config. If a site survey finds the address isn't serviceable, the order branches to an alternative-technology path. A field install that the customer isn't present for is rescheduled, and only a tested, active service is handed to billing to go live." },
  { name: "billing-claims", prompt: "A medical practice bills payers across Coding, Billing, and Collections lanes, with Billing split into Submission and Follow-up sub-teams. An encounter is coded, then a submission stage scrubs the claim, checks eligibility, and submits; scrubbing is its own process of validating codes and catching edits, and a failed edit loops back for correction. A denied claim opens an appeals sub-process of review, rebuttal, and resubmission, looping until paid or written off. If a payer doesn't respond within the timely-filing window, the claim is escalated. Paid claims are reconciled; patient balances move to collections." },
  { name: "loan-collections", prompt: "A lender manages arrears across Early Collections, Late Collections, and Recovery lanes, with Late Collections split into Negotiators and a Supervisor. An account enters a collections stage of contact attempts, an affordability assessment, and an arrangement; the assessment branches into a hardship sub-process when the borrower is struggling. A broken arrangement loops the account back to contact, and after a number of failed cycles it escalates to the next lane. If the borrower doesn't respond within the regulatory timeframe, a formal notice is issued, and unresolved accounts pass to recovery." },
  { name: "clinical-trial-intake", prompt: "A research site enrols a participant across Recruitment, Clinical, and Regulatory lanes, with Clinical split into Coordinators and Investigators. A candidate is pre-screened, then an eligibility stage runs consent, screening tests, and an investigator review; the screening tests are their own sub-process and an out-of-range result triggers a confirmatory re-test. Depending on eligibility the candidate is enrolled, screen-failed, or referred for a waiver decision. If consent isn't completed within the screening window, the candidate is withdrawn, and a protocol deviation loops back to investigator review." },
  { name: "rfp-vendor-evaluation", prompt: "A buyer evaluates vendors across Procurement and Stakeholder lanes, with Stakeholders split into Technical, Security, and Finance reviewers. After shortlisting, an evaluation stage runs technical, security, and financial assessments in parallel; the security assessment branches into a deeper audit for vendors handling sensitive data. Findings are consolidated and, if a vendor has gaps, they're asked to remediate and are re-assessed (a loop). Depending on the consolidated score a vendor is selected, held, or rejected. If a vendor misses the clarification deadline, they're eliminated, and the winner proceeds to contracting." },
  { name: "underwriting-commercial", prompt: "A commercial insurer underwrites a policy across Broking, Underwriting, and Actuarial lanes, with Underwriting split into Underwriters and a Senior Referral desk. A submission is triaged, then an underwriting stage assesses the risk, prices it, and sets terms; risk assessment is its own sub-process of surveying the risk and modelling losses, and a large exposure is referred to the senior desk. If information is missing the broker is asked and the stage repeats once it's supplied. Depending on appetite the risk is quoted, declined, or referred to reinsurance. A quote not accepted within its validity period lapses." },
  { name: "onboarding-saas-enterprise", prompt: "A SaaS vendor onboards an enterprise customer across Customer Success, Implementation, and Support lanes, with Implementation split into Configuration and Integration sub-teams. After kickoff, an implementation stage runs configuration, data migration, and integration in sequence; data migration is its own sub-process of extract, transform, and load, and a validation failure loops back to transform. Integration branches by system landscape into a standard or a custom path. A user-acceptance gate either signs off or sends defects back for rework. If the customer doesn't sign off within the agreed window, the go-live is rescheduled and Support is briefed." },
  { name: "litigation-discovery", prompt: "A law firm runs a litigation matter across Partners, Associates, and Paralegals lanes, with Associates split into Litigation and Research sub-teams. After intake, a discovery stage collects documents, reviews them, and prepares production; document review is its own sub-process of a first-pass review, a privilege check, and a quality check, and any document marked uncertain loops back for a second review. Depending on findings the matter proceeds to settlement talks or to trial preparation, and if opposing counsel raises a deficiency the production is revised and reissued. If a court-imposed deadline is about to pass, the team files for an extension, and a settlement reached at any point ends the matter early." },
  { name: "loan-restructure", prompt: "A bank restructures a distressed loan across Relationship, Credit, and Approvals lanes, with Credit split into Analysts and a Credit Committee. After a hardship request, an assessment stage reviews the borrower's position, models repayment options, and recommends a structure; the modelling is its own sub-process of stress-testing each option, and an option that fails the stress test is discarded and the modelling repeats. Depending on the exposure the recommendation is approved by an analyst, the committee, or escalated to the board, and a rejected proposal loops back for re-modelling. If the borrower doesn't return signed terms within the offer period, the original terms stand and the account moves to monitoring." },
];
