-- Repair container ownership (B47 parentage) in the example catalogues.
-- Generated by scripts/fix-example-parentage.ts — review before running.
-- Every statement is guarded on the element id AND its current parent at
-- that exact JSON path, so it no-ops if the package differs. Safe to re-run.
BEGIN;

-- Simulation: Aardwolf Loans — As-is vs To-be (aardwolf-loan-comparison) — 4 fix(es)
UPDATE "SimulationExample" SET package = jsonb_set(package, '{diagrams,0,data,elements,23,parentId}', '"lHome"'::jsonb, true), "updatedAt" = NOW()
 WHERE slug = 'aardwolf-loan-comparison'
   AND package #>> '{diagrams,0,data,elements,23,id}' = 'gxType'
   AND (package #>> '{diagrams,0,data,elements,23,parentId}' = 'lAssess');
UPDATE "SimulationExample" SET package = jsonb_set(package, '{diagrams,0,data,elements,26,parentId}', '"lHome"'::jsonb, true), "updatedAt" = NOW()
 WHERE slug = 'aardwolf-loan-comparison'
   AND package #>> '{diagrams,0,data,elements,26,id}' = 'gxTypeMerge'
   AND (package #>> '{diagrams,0,data,elements,26,parentId}' = 'lAssess');
UPDATE "SimulationExample" SET package = jsonb_set(package, '{diagrams,1,data,elements,20,parentId}', '"lHome"'::jsonb, true), "updatedAt" = NOW()
 WHERE slug = 'aardwolf-loan-comparison'
   AND package #>> '{diagrams,1,data,elements,20,id}' = 'gw_type'
   AND (package #>> '{diagrams,1,data,elements,20,parentId}' = 'lAI');
UPDATE "SimulationExample" SET package = jsonb_set(package, '{diagrams,1,data,elements,31,parentId}', '"lHome"'::jsonb, true), "updatedAt" = NOW()
 WHERE slug = 'aardwolf-loan-comparison'
   AND package #>> '{diagrams,1,data,elements,31,id}' = 'gw_type_merge'
   AND (package #>> '{diagrams,1,data,elements,31,parentId}' = 'lPers');

-- Risk & Controls: Order-to-Cash — Governance & Controls (order-to-cash-grc) — 2 fix(es)
UPDATE "RiskControlExample" SET package = jsonb_set(package, '{diagrams,16,data,elements,6,parentId}', '"lOP"'::jsonb, true), "updatedAt" = NOW()
 WHERE slug = 'order-to-cash-grc'
   AND package #>> '{diagrams,16,data,elements,6,id}' = 'gwComplete'
   AND (package #>> '{diagrams,16,data,elements,6,parentId}' = 'lCSR');
UPDATE "RiskControlExample" SET package = jsonb_set(package, '{diagrams,16,data,elements,14,parentId}', '"lOP"'::jsonb, true), "updatedAt" = NOW()
 WHERE slug = 'order-to-cash-grc'
   AND package #>> '{diagrams,16,data,elements,14,id}' = 'gwMergeComplete'
   AND (package #>> '{diagrams,16,data,elements,14,parentId}' = 'lCSR');

COMMIT;
