-- Abracadabra / Assist: the 'Suggestion' chip and its target template (generated 2026-09-15 from the local seeds)
-- Idempotent: re-running changes nothing. Run in one transaction.
BEGIN;

-- 1. Rename the intent row in place (keeps its id and any admin keyword edits) and give it its target.
UPDATE "IntentKeywordMap" SET label = 'Suggestion', "targetTemplateName" = COALESCE("targetTemplateName", 'Send Notification'), "updatedAt" = now() WHERE label = 'Notification';

-- 2. The full Assist / NL Rules catalogue — inserted only where the label is missing (prod may never have been seeded).
INSERT INTO "IntentKeywordMap" (id, label, keywords, action, "diagramType", "defaultLabel", "targetCategory", "targetTemplateName", "sortOrder", "createdAt", "updatedAt")
  SELECT gen_random_uuid()::text, 'Approval', ARRAY['approve', 'approval', 'sign-off', 'sign off', 'authorise', 'authorize', 'review', 'endorse', 'ratify']::text[], 'suggest-template', 'all', NULL, 'Approvals', NULL, 10, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM "IntentKeywordMap" WHERE label = 'Approval');
INSERT INTO "IntentKeywordMap" (id, label, keywords, action, "diagramType", "defaultLabel", "targetCategory", "targetTemplateName", "sortOrder", "createdAt", "updatedAt")
  SELECT gen_random_uuid()::text, 'Rejection', ARRAY['reject', 'rejection', 'decline', 'deny', 'refuse']::text[], 'suggest-template', 'all', NULL, 'Approvals', NULL, 20, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM "IntentKeywordMap" WHERE label = 'Rejection');
INSERT INTO "IntentKeywordMap" (id, label, keywords, action, "diagramType", "defaultLabel", "targetCategory", "targetTemplateName", "sortOrder", "createdAt", "updatedAt")
  SELECT gen_random_uuid()::text, 'Escalation', ARRAY['escalate', 'escalation', 'expedite']::text[], 'suggest-template', 'all', NULL, 'Exceptions', NULL, 30, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM "IntentKeywordMap" WHERE label = 'Escalation');
INSERT INTO "IntentKeywordMap" (id, label, keywords, action, "diagramType", "defaultLabel", "targetCategory", "targetTemplateName", "sortOrder", "createdAt", "updatedAt")
  SELECT gen_random_uuid()::text, 'Exception', ARRAY['error', 'exception', 'fault', 'failure', 'fail']::text[], 'suggest-template', 'all', NULL, 'Exceptions', NULL, 40, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM "IntentKeywordMap" WHERE label = 'Exception');
INSERT INTO "IntentKeywordMap" (id, label, keywords, action, "diagramType", "defaultLabel", "targetCategory", "targetTemplateName", "sortOrder", "createdAt", "updatedAt")
  SELECT gen_random_uuid()::text, 'Suggestion', ARRAY['notify', 'notification', 'alert', 'email', 'inform', 'remind', 'reminder']::text[], 'suggest-template', 'all', NULL, 'Events', 'Send Notification', 50, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM "IntentKeywordMap" WHERE label = 'Suggestion');
INSERT INTO "IntentKeywordMap" (id, label, keywords, action, "diagramType", "defaultLabel", "targetCategory", "targetTemplateName", "sortOrder", "createdAt", "updatedAt")
  SELECT gen_random_uuid()::text, 'Payment', ARRAY['pay', 'payment', 'invoice', 'billing', 'refund', 'settle']::text[], 'suggest-template', 'all', NULL, 'Approvals', NULL, 60, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM "IntentKeywordMap" WHERE label = 'Payment');
INSERT INTO "IntentKeywordMap" (id, label, keywords, action, "diagramType", "defaultLabel", "targetCategory", "targetTemplateName", "sortOrder", "createdAt", "updatedAt")
  SELECT gen_random_uuid()::text, 'Review loop', ARRAY['rework', 'revise', 'revision', 'amend', 'correct']::text[], 'suggest-template', 'all', NULL, 'Loops', NULL, 70, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM "IntentKeywordMap" WHERE label = 'Review loop');
INSERT INTO "IntentKeywordMap" (id, label, keywords, action, "diagramType", "defaultLabel", "targetCategory", "targetTemplateName", "sortOrder", "createdAt", "updatedAt")
  SELECT gen_random_uuid()::text, 'Instructions', ARRAY['per the', 'according to', 'policy', 'procedure', 'guideline', 'instructions', 'template', 'checklist', 'standard', 'rules', 'as per']::text[], 'add-input-data-object', 'all', 'Instructions', NULL, NULL, 80, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM "IntentKeywordMap" WHERE label = 'Instructions');
INSERT INTO "IntentKeywordMap" (id, label, keywords, action, "diagramType", "defaultLabel", "targetCategory", "targetTemplateName", "sortOrder", "createdAt", "updatedAt")
  SELECT gen_random_uuid()::text, 'Output Doc', ARRAY['produce', 'prepare', 'create', 'draft', 'write', 'generate', 'update', 'issue', 'compile', 'report', 'letter', 'document', 'certificate', 'record']::text[], 'add-output-data-object', 'all', 'Output Doc', NULL, NULL, 90, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM "IntentKeywordMap" WHERE label = 'Output Doc');

-- 3. The 'Send Notification' built-in template (send task → 'Acknowledged' message catch → Continue), owned by the earliest user, as the seed does.
INSERT INTO "DiagramTemplate" (id, name, "diagramType", "templateType", description, "thumbnailSvg", "group", data, "userId", "createdAt", "updatedAt")
  SELECT gen_random_uuid()::text, 'Send Notification', 'bpmn', 'builtin', 'A send task that notifies a party, then a message catch that waits for their acknowledgement — delete the catch if no reply is expected.', $svg$<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 538 94" preserveAspectRatio="xMidYMid meet"><defs><marker id="tmarr" markerWidth="7" markerHeight="7" refX="6" refY="3" orient="auto"><path d="M0,0 L6,3 L0,6 z" fill="#475569"/></marker><marker id="tmopen" markerWidth="8" markerHeight="8" refX="6.5" refY="3" orient="auto"><path d="M0,0 L6,3 L0,6" fill="none" stroke="#475569" stroke-width="1"/></marker><marker id="tmcirc" markerWidth="7" markerHeight="7" refX="3.2" refY="3" orient="auto"><circle cx="3" cy="3" r="2" fill="#ffffff" stroke="#475569" stroke-width="1"/></marker></defs><path d="M 144.0 47.0 L 168.0 47.0 L 229.0 47.0 L 249.0 47.0" fill="none" stroke="#475569" stroke-width="1.2" vector-effect="non-scaling-stroke"  marker-end="url(#tmarr)"/><path d="M 289.0 47.0 L 309.0 47.0 L 370.0 47.0 L 394.0 47.0" fill="none" stroke="#475569" stroke-width="1.2" vector-effect="non-scaling-stroke"  marker-end="url(#tmarr)"/><rect x="14" y="14" width="130" height="66" rx="6" fill="#dbeafe" stroke="#3b82f6" stroke-width="1.4" vector-effect="non-scaling-stroke"/><text x="79.0" y="51.0" text-anchor="middle" font-size="11" fill="#0f172a" font-family="sans-serif">Send notificati…</text><circle cx="269.0" cy="47.0" r="20" fill="#fff7ed" stroke="#ca8a04" stroke-width="1.4" vector-effect="non-scaling-stroke"/><circle cx="269.0" cy="47.0" r="17.0" fill="none" stroke="#ca8a04" stroke-width="1" vector-effect="non-scaling-stroke"/><rect x="259.0" y="40.4" width="20.0" height="13.2" fill="none" stroke="#ca8a04" stroke-width="1.2" vector-effect="non-scaling-stroke"/><path d="M259.0,40.4 L269.0,47.0 L279.0,40.4" fill="none" stroke="#ca8a04" stroke-width="1.2" vector-effect="non-scaling-stroke"/><text x="269.0" y="78.0" text-anchor="middle" font-size="10" fill="#0f172a" font-family="sans-serif">Acknowledged</text><rect x="394" y="14" width="130" height="66" rx="6" fill="#dbeafe" stroke="#3b82f6" stroke-width="1.4" vector-effect="non-scaling-stroke"/><text x="459.0" y="51.0" text-anchor="middle" font-size="11" fill="#0f172a" font-family="sans-serif">Continue</text></svg>$svg$, 'Events',
         $json${"elements": [{"x": 15, "y": 57, "id": "n", "type": "task", "label": "Send notification", "width": 130, "height": 66, "taskType": "send", "properties": {}}, {"x": 250, "y": 70, "id": "ack", "type": "intermediate-event", "label": "Acknowledged", "width": 40, "height": 40, "eventType": "message", "properties": {"flowType": "catching"}}, {"x": 395, "y": 57, "id": "c", "type": "task", "label": "Continue", "width": 130, "height": 66, "properties": {}}], "connectors": [{"id": "c0", "type": "sequence", "sourceId": "n", "targetId": "ack", "waypoints": [{"x": 80, "y": 90}, {"x": 145, "y": 90}, {"x": 169, "y": 90}, {"x": 230, "y": 90}, {"x": 250, "y": 90}, {"x": 270, "y": 90}], "sourceSide": "right", "targetSide": "left", "routingType": "rectilinear", "directionType": "directed", "sourceOffsetAlong": 0.5, "targetOffsetAlong": 0.5, "sourceInvisibleLeader": true, "targetInvisibleLeader": true}, {"id": "c1", "type": "sequence", "sourceId": "ack", "targetId": "c", "waypoints": [{"x": 270, "y": 90}, {"x": 290, "y": 90}, {"x": 310, "y": 90}, {"x": 371, "y": 90}, {"x": 395, "y": 90}, {"x": 460, "y": 90}], "sourceSide": "right", "targetSide": "left", "routingType": "rectilinear", "directionType": "directed", "sourceOffsetAlong": 0.5, "targetOffsetAlong": 0.5, "sourceInvisibleLeader": true, "targetInvisibleLeader": true}]}$json$::jsonb, (SELECT id FROM "User" ORDER BY "createdAt" ASC LIMIT 1), now(), now()
  WHERE EXISTS (SELECT 1 FROM "User") AND NOT EXISTS (SELECT 1 FROM "DiagramTemplate" WHERE name = 'Send Notification' AND "diagramType" = 'bpmn' AND "templateType" = 'builtin');

-- 4. Check: expect one 'Suggestion' row naming 'Send Notification', no 'Notification' row, and one template.
SELECT label, "targetTemplateName" FROM "IntentKeywordMap" WHERE label IN ('Suggestion', 'Notification');
SELECT name, "group" FROM "DiagramTemplate" WHERE name = 'Send Notification' AND "templateType" = 'builtin';
COMMIT;
