/**
 * "✎ Correct" on the phone (2026-09-29, mobile voice stage 3): look at a
 * generated diagram, say what is wrong ("the approval happens before
 * payment"), and re-generate. The correction goes on the END of the prompt the
 * diagram was generated from (promptPreambles.withCorrection), so corrections
 * accumulate and a later re-generate — here or on the desktop — keeps them.
 *
 * It replaces the WHOLE diagram, review comments included; the version it
 * replaces stays in the diagram's history (generateJob: ensureCurrentInHistory).
 * A diagram drawn from a photo or an image is re-generated WITH that image —
 * laid out as it was drawn (Free Form) when the diagram was, unless the person
 * turns that off (2026-09-29).
 *
 * ONE rule for what can be re-generated: the phone offers ✎ Correct by it, and
 * POST /api/diagrams/[id]/generate refuses a replace by it.
 */
import type { DiagramData } from "@/app/lib/diagram/types";
import { correctionAdded, isWhiteboardPhotoPrompt, withCorrection } from "@/app/lib/ai/promptPreambles";
import { imageNameInPrompt, regenerateFreeForm } from "@/app/lib/ai/sourceImage";

export type CorrectionRefusal =
  /** No prompt to correct. */
  | "not_generated"
  /** Drawn from an image that was never kept — the words alone would draw something else. */
  | "image_not_kept"
  /** Drawn from an attached document, which is never kept. */
  | "document_not_kept";

export type CorrectionSource =
  | {
    ok: true;
    /** The prompt the diagram was generated from. */
    basePrompt: string;
    /** The kept image to send again, when it was drawn from one. */
    sourceImageId: string | null;
    imageName: string | null;
    /** It was laid out as its image was drawn (Free Form) — the re-generate's starting choice. */
    freeForm: boolean;
  }
  | { ok: false; reason: CorrectionRefusal };

/**
 * The words the consoles and the Partner API put in a prompt when a document
 * is attached — how a diagram generated before the record said so is known to
 * have come from one.
 */
const DOCUMENT_PROMPT_MARKERS = ["I have attached a document", "The attached document describes the process"];

/** Can this diagram be re-generated with a correction — and from what? */
export function correctionSource(data: DiagramData): CorrectionSource {
  const g = data.aiGeneration;
  const basePrompt = (g?.promptText ?? "").trim();
  if (!g || !basePrompt) return { ok: false, reason: "not_generated" };
  // The generation's own record where there is one; the prompt's words for
  // diagrams generated before it existed (as the desktop's Regenerate decides).
  const fromDocument = g.fromDocument ?? DOCUMENT_PROMPT_MARKERS.some((m) => basePrompt.includes(m));
  if (fromDocument) return { ok: false, reason: "document_not_kept" };
  const img = g.sourceImage?.id ? g.sourceImage : null;
  const fromImage = g.fromImage ?? (!!imageNameInPrompt(basePrompt) || isWhiteboardPhotoPrompt(basePrompt));
  if (!img && (fromImage || isWhiteboardPhotoPrompt(basePrompt))) return { ok: false, reason: "image_not_kept" };
  // Free Form needs the image; without one a re-generate is laid out normally.
  const freeForm = !!img && regenerateFreeForm(g, data.relaxedLayout) === true;
  return { ok: true, basePrompt, sourceImageId: img?.id ?? null, imageName: img?.name ?? null, freeForm };
}

/** Why ✎ Correct cannot re-generate this diagram, in the person's terms. */
export function correctionRefusalText(reason: CorrectionRefusal): string {
  switch (reason) {
    case "not_generated": return "This diagram wasn’t generated by the AI, so there’s no prompt to correct.";
    case "image_not_kept": return "This diagram was drawn from an image that wasn’t kept, so it can’t be re-generated on the phone. Re-generate it on the desktop with the image.";
    case "document_not_kept": return "This diagram was drawn from an attached document, which isn’t kept, so it can’t be re-generated on the phone. Re-generate it on the desktop with the document.";
  }
}

/**
 * What POST …/generate is sent: the corrected prompt, the image again with the
 * Free Form choice (the diagram's own unless the person changed it), and an
 * explicit replace of the version on screen.
 */
export function correctionRequest(
  src: Extract<CorrectionSource, { ok: true }>,
  words: string,
  version: number,
  freeForm: boolean = src.freeForm,
): { prompt: string; version: number; replace: true; sourceImageId?: string; freeForm?: boolean } {
  return {
    prompt: withCorrection(src.basePrompt, words),
    version,
    replace: true,
    ...(src.sourceImageId ? { sourceImageId: src.sourceImageId, freeForm } : {}),
  };
}

/** The correction a run was started with, read back from its prompt — so a failed run gives the words back. */
export function correctionFromRun(data: DiagramData, runPrompt: string): string | null {
  const src = correctionSource(data);
  return src.ok ? correctionAdded(src.basePrompt, runPrompt) : null;
}

/**
 * Why a re-generate did not happen, in the phone's terms: the server's
 * messages are written for Generate on an empty diagram ("Tap Generate…",
 * "take the photo again"), which a correction has no button for.
 */
export function correctionErrorText(code: string | null | undefined, fallback: string): string {
  switch (code) {
    case "worker_lost": return "It was interrupted before it finished.";
    case "image_gone":
    case "photo_needed":
    case "image_mismatch": return "The image it was drawn from can no longer be found, so it can’t be re-generated on the phone.";
    case "image_too_large": return "The image it was drawn from is too large for the AI to read.";
    default: return fallback;
  }
}

/** How many review comments a re-generate would replace (unsaved ones included). */
export function reviewCommentCount(data: DiagramData): number {
  return (data.elements ?? []).filter((e) => e.type === "review-comment").length;
}

/** The warning shown before a re-generate, in plain words. */
export function replaceWarning(comments: number, unsaved: boolean): string {
  const c = comments === 0 ? ""
    : comments === 1 ? ", and its 1 review comment,"
    : `, and its ${comments} review comments,`;
  return `This replaces the whole diagram${c} with a new one.`
    + (unsaved ? " Comments you haven’t saved are lost." : "")
    + " The current version stays in the diagram’s history, so it can be restored on the desktop.";
}
