import { NextResponse } from "next/server";
import { cookies } from "next/headers";
import { auth } from "@/auth";
import { prisma } from "@/app/lib/db";
import { requireDiagramAccess, OrgContextError } from "@/app/lib/auth/orgContext";
import { diagramFreshness, type FreshnessNote } from "@/app/lib/valueChain/staleness";
import { latestTemplateVersion, MD_PROMPT_TYPES, type MdPromptType } from "@/app/lib/valueChain/promptTemplates";
import { processCodeForDiagram } from "@/app/lib/valueChain/diagramSource";

type Params = { params: Promise<{ id: string }> };

/**
 * GET /api/diagrams/[id]/freshness — is this diagram still a picture of its prompt?
 *
 * Paul, 2026-09-06: "any existing diagram that was regenerated before the prompt
 * regeneration timestamp must also have a message added in the diagram
 * properties panel alerting the user."
 *
 * Cheap enough to call on every open: one diagram read the caller has already
 * been authorised for, and at most one prompt lookup. Returns `notes: []` for
 * anything that is current or was never generated from the repository, because
 * a panel that always says something is a panel people stop reading.
 */
export async function GET(_req: Request, { params }: Params) {
  const session = await auth();
  if (!session?.user?.id) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const { id } = await params;
  try {
    await requireDiagramAccess(session, await cookies(), id, "view");
  } catch (err) {
    if (err instanceof OrgContextError) return NextResponse.json({ error: err.message }, { status: err.status });
    throw err;
  }

  const diagram = await prisma.diagram.findUnique({ where: { id }, select: { name: true, type: true, data: true } });
  if (!diagram) return NextResponse.json({ error: "Not found" }, { status: 404 });

  const data = (diagram.data as Record<string, unknown>) ?? {};
  const gen = (data.aiGeneration as Record<string, unknown> | undefined) ?? undefined;
  // Not generated by us at all — nothing to be stale against.
  if (!gen) return NextResponse.json({ notes: [] as FreshnessNote[] });

  const type: MdPromptType = MD_PROMPT_TYPES.includes(diagram.type as MdPromptType)
    ? (diagram.type as MdPromptType) : "bpmn";

  // The stamp is authoritative where it exists; the name is the fallback that
  // makes every diagram generated BEFORE the stamp shipped answerable too —
  // which is the whole population Paul is asking about.
  const source = (gen.source as Record<string, unknown> | undefined) ?? undefined;
  const processCode = typeof source?.processCode === "string" && source.processCode
    ? source.processCode
    : processCodeForDiagram(diagram.name);

  let promptRegeneratedAt: Date | null = null;
  if (processCode) {
    const row = await prisma.valueChainPrompt.findFirst({
      where: { type, processCode },
      select: { generatedAt: true },
      orderBy: { generatedAt: "desc" },
    });
    promptRegeneratedAt = row?.generatedAt ?? null;
  }

  const notes = diagramFreshness({
    diagramGeneratedAt: typeof gen.generatedAt === "string" ? gen.generatedAt : null,
    promptRegeneratedAt,
    templateVersionAtGeneration: typeof source?.templateVersion === "number" ? source.templateVersion : null,
    currentTemplateVersion: latestTemplateVersion(type).version,
    hasPlan: !!gen.plan,
    type,
  });

  return NextResponse.json({ notes, processCode: processCode || null });
}
