/**
 * T5258 — AI Model Selection, slices 4 and 5 (Paul, 2026-10-05): "Individual users should not be able to choose what model they use" and
 * "Only OrgAdmins and SuperAdmins should ever see what model is being used in Diagramatix. Check all messages to users."
 *   • no model picker for anyone but a SuperAdmin in SuperAdmin view (and none when SuperAdmin is acting as a customer level);
 *   • no model name on a customer screen, in a status line, or over the wire to an ordinary user.
 */
import { describe, expect, it } from "vitest";
import { readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";

const read = (p: string) => readFileSync(p, "utf8");
function files(dir: string): string[] {
  const out: string[] = [];
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    if (e.name === "node_modules" || e.name === "generated") continue;
    const p = join(dir, e.name);
    if (e.isDirectory()) out.push(...files(p));
    else if (/\.(ts|tsx)$/.test(e.name)) out.push(p);
  }
  return out;
}
const rel = (f: string) => f.split("\\").join("/");

describe("T5258 no picker for users", () => {
  it("the AI panels offer the model drop-down only to a SuperAdmin in SuperAdmin view", () => {
    for (const f of ["app/(dashboard)/diagram/[id]/AiPanel.tsx", "app/(dashboard)/diagram/[id]/PlanPanel.tsx"]) {
      const src = read(f);
      const at = src.indexOf("<ModelSelect");
      expect(at, f).toBeGreaterThan(-1);
      expect(src.slice(Math.max(0, at - 700), at), f).toContain("isAdmin && !superAdminHidden && aiModels.length > 0");
    }
  });
  it("Regenerate shows its drop-down only when canSeeModel, which is the SuperAdmin flag", () => {
    const src = read("app/components/canvas/PropertiesPanel.tsx");
    expect(src).toContain("{canSeeModel && (");
    expect(src).toContain("canSeeModel={_isAdmin}");
  });
  it("a request that names a model is ignored for everyone but a SuperAdmin (the server end of it)", () => {
    expect(read("app/lib/ai/modelAccess.ts")).toContain("if (!superAdminAllowed) return currentModelId;");
  });
});

describe("T5258 no model name for users", () => {
  it("/api/ai/models gives an ordinary user nothing — no current model, no list — before it resolves anything", () => {
    const src = read("app/api/ai/models/route.ts");
    const gate = src.indexOf("if (!isSuperuser(session)) return NextResponse.json({ current: null, models: [] });");
    expect(gate).toBeGreaterThan(-1);
    expect(gate).toBeLessThan(src.indexOf("resolveOrgModel("));
  });
  it("AI Generate and the plan panel say “the AI”, not a model, unless a SuperAdmin is looking", () => {
    expect(read("app/(dashboard)/diagram/[id]/ai-generate/AiGenerateScreen.tsx")).toContain('const modelLabel = saAvailable ? (aiModels.find((m) => m.id === (model || currentAiModelId))?.label || "the AI model") : "the AI";');
    const plan = read("app/(dashboard)/diagram/[id]/PlanPanel.tsx");
    expect(plan).toContain('const mLabel = isAdmin && !superAdminHidden ? (aiModels.find((m) => m.id === (model || currentAiModelId))?.label || "the AI model") : "the AI";');
    expect(plan).toContain('setStatus("Asking the AI for a staff narrative (15–30 s)…");');
  });
  it("the Properties panel's “Prompt written by … / drawn by …” line is for a SuperAdmin only", () => {
    expect(read("app/components/canvas/PropertiesPanel.tsx")).toContain("{aiPromptModel && _isAdmin && (");
  });
  it("no screen carries a hard-coded model name in what it says to the person (comments aside)", () => {
    const bad: string[] = [];
    for (const f of [...files("app/(dashboard)/diagram"), ...files("app/components"), ...files("app/m")]) {
      read(f).split("\n").forEach((l, i) => {
        if (/^\s*(\/\/|\*|\/\*|\{\/\*)/.test(l)) return;
        if (/["'`][^"'`]*\b(Asking|Powered by|Generated by|drawn by|written by)\s+(Sonnet|Opus|Haiku|Fable|Claude|Kimi|Gemini|GPT)/.test(l)) bad.push(`${rel(f)}:${i + 1}: ${l.trim().slice(0, 100)}`);
      });
    }
    expect(bad).toEqual([]);
  });
  it("a ratchet: a screen outside the admin areas that calls aiModelLabel() must be behind a SuperAdmin flag", () => {
    const ok = (r: string) => r.startsWith("app/(dashboard)/dashboard/admin/") || r.startsWith("app/(dashboard)/dashboard/org-admin/") || r.startsWith("app/(dashboard)/dashboard/ai-usage/");
    const bad: string[] = [];
    for (const f of [...files("app/(dashboard)"), ...files("app/components"), ...files("app/m")].filter((x) => x.endsWith(".tsx"))) {
      const r = rel(f);
      if (ok(r)) continue;
      const src = read(f);
      if (src.includes("aiModelLabel(") && !/_isAdmin|isAdmin/.test(src)) bad.push(r);
    }
    expect(bad).toEqual([]);
  });
  it("no server message to the person interpolates a model (the export-prompt filename is SuperAdmin-only)", () => {
    const bad: string[] = [];
    for (const f of [...files("app/api"), ...files("app/lib/ai")]) {
      const r = rel(f);
      if (r.startsWith("app/api/admin/") || r === "app/api/ai/generate-bpmn/export-prompt/route.ts") continue;
      read(f).split("\n").forEach((l, i) => {
        if (/^\s*(\/\/|\*|\/\*)/.test(l) || /console\.|log\(/.test(l)) return;
        if (/\berror:\s*[`"'][^`"']*\$\{[^}]*[mM]odel/.test(l)) bad.push(`${r}:${i + 1}: ${l.trim().slice(0, 100)}`);
      });
    }
    expect(bad).toEqual([]);
  });
});
